// Full Box API v2 reference — https://developer.box.com/reference/
// Base URL for all endpoints: https://api.box.com/2.0/
// Upload endpoint base: https://upload.box.com/api/2.0/

export const boxAPIs = [

  // ── FILES — Read ──────────────────────────────────────────────────────────
  {
    id: 'files-get',
    group: 'Files — Read',
    name: 'Get File Info',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}',
    description: 'Returns full metadata for a specific file — name, size, modified date, owner, shared link, etc.',
    params: [
      { key: 'file_id', type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Numeric Box file ID.' },
      { key: 'fields',  type: 'query', required: false, hint: 'e.g. name,size,modified_at,owned_by,shared_link', description: 'Comma-separated fields to include.' },
    ],
  },
  {
    id: 'files-download',
    group: 'Files — Read',
    name: 'Download File',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}/content',
    description: 'Downloads the actual file content. Returns a redirect to the download URL.',
    params: [
      { key: 'file_id',    type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID.' },
      { key: 'version',    type: 'query', required: false, hint: 'e.g. 1', description: 'Specific file version to download.' },
    ],
  },
  {
    id: 'files-get-thumbnail',
    group: 'Files — Read',
    name: 'Get File Thumbnail',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}/thumbnail.{extension}',
    description: 'Returns a thumbnail image (PNG/JPG) for an image or document file.',
    params: [
      { key: 'file_id',   type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID.' },
      { key: 'extension', type: 'path', required: true, hint: 'e.g. png', description: 'Thumbnail format: png or jpg.' },
      { key: 'min_width',  type: 'query', required: false, hint: 'e.g. 256', description: 'Minimum width of the thumbnail.' },
      { key: 'min_height', type: 'query', required: false, hint: 'e.g. 256', description: 'Minimum height of the thumbnail.' },
    ],
  },
  {
    id: 'files-get-versions',
    group: 'Files — Read',
    name: 'List File Versions',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}/versions',
    description: 'Returns a list of all past versions of a file.',
    params: [
      { key: 'file_id', type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID.' },
      { key: 'limit',   type: 'query', required: false, hint: 'e.g. 100', description: 'Max versions to return.' },
      { key: 'offset',  type: 'query', required: false, hint: 'e.g. 0', description: 'Pagination offset.' },
    ],
  },
  {
    id: 'files-get-collaborations',
    group: 'Files — Read',
    name: 'List File Collaborations',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}/collaborations',
    description: 'Returns all collaborations (shared access) for a specific file.',
    params: [
      { key: 'file_id', type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID.' },
      { key: 'fields',  type: 'query', required: false, hint: 'e.g. id,type,accessible_by,role', description: 'Fields to include.' },
      { key: 'limit',   type: 'query', required: false, hint: 'e.g. 100', description: 'Max results.' },
    ],
  },
  {
    id: 'files-get-comments',
    group: 'Files — Read',
    name: 'List File Comments',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}/comments',
    description: 'Returns all comments added to a specific file.',
    params: [
      { key: 'file_id', type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID.' },
      { key: 'fields',  type: 'query', required: false, hint: 'e.g. id,message,created_by,created_at', description: 'Fields to include.' },
    ],
  },
  {
    id: 'files-get-tasks',
    group: 'Files — Read',
    name: 'List File Tasks',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}/tasks',
    description: 'Returns all tasks associated with a file.',
    params: [
      { key: 'file_id', type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID.' },
    ],
  },
  {
    id: 'files-get-metadata',
    group: 'Files — Read',
    name: 'List File Metadata Instances',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}/metadata',
    description: 'Returns all metadata instances applied to a file.',
    params: [
      { key: 'file_id', type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID.' },
    ],
  },
  {
    id: 'files-get-metadata-scope',
    group: 'Files — Read',
    name: 'Get File Metadata (by Template)',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}/metadata/{scope}/{template_key}',
    description: 'Returns a specific metadata instance on a file by scope and template key.',
    params: [
      { key: 'file_id',      type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID.' },
      { key: 'scope',        type: 'path', required: true, hint: 'e.g. global or enterprise', description: 'Metadata scope.' },
      { key: 'template_key', type: 'path', required: true, hint: 'e.g. properties', description: 'Metadata template key.' },
    ],
  },
  {
    id: 'files-get-watermark',
    group: 'Files — Read',
    name: 'Get File Watermark',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}/watermark',
    description: 'Returns watermark information for a file.',
    params: [
      { key: 'file_id', type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID.' },
    ],
  },
  {
    id: 'files-get-trash',
    group: 'Files — Read',
    name: 'Get Trashed File',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}/trash',
    description: 'Returns metadata about a file that has been moved to trash.',
    params: [
      { key: 'file_id', type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID.' },
    ],
  },

  // ── FILES — Write ─────────────────────────────────────────────────────────
  {
    id: 'files-update',
    group: 'Files — Write',
    name: 'Update File',
    method: 'PUT',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}',
    description: 'Updates a file\'s name, description, tags, or parent folder.',
    params: [
      { key: 'file_id',     type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID.' },
      { key: 'name',        type: 'body', required: false, hint: 'e.g. new-name.pdf', description: 'New file name.' },
      { key: 'description', type: 'body', required: false, hint: 'e.g. Q4 report', description: 'New description.' },
      { key: 'parent.id',   type: 'body', required: false, hint: 'e.g. 0', description: 'New parent folder ID to move into.' },
    ],
  },
  {
    id: 'files-copy',
    group: 'Files — Write',
    name: 'Copy File',
    method: 'POST',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}/copy',
    description: 'Creates a copy of a file in the specified folder.',
    params: [
      { key: 'file_id',    type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID to copy.' },
      { key: 'parent.id', type: 'body', required: true, hint: 'e.g. 0', description: 'Destination folder ID.' },
      { key: 'name',       type: 'body', required: false, hint: 'e.g. copy-of-report.pdf', description: 'Optional new name for the copy.' },
    ],
  },
  {
    id: 'files-delete',
    group: 'Files — Write',
    name: 'Delete File',
    method: 'DELETE',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}',
    description: 'Moves a file to the trash.',
    params: [
      { key: 'file_id', type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID to delete.' },
    ],
  },
  {
    id: 'files-delete-trash',
    group: 'Files — Write',
    name: 'Permanently Delete File (from Trash)',
    method: 'DELETE',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}/trash',
    description: 'Permanently deletes a file from the trash. Cannot be undone.',
    params: [
      { key: 'file_id', type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID.' },
    ],
  },
  {
    id: 'files-delete-version',
    group: 'Files — Write',
    name: 'Delete File Version',
    method: 'DELETE',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}/versions/{version_id}',
    description: 'Deletes a specific version of a file.',
    params: [
      { key: 'file_id',    type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID.' },
      { key: 'version_id', type: 'path', required: true, hint: 'e.g. 1234567890', description: 'Version ID to delete.' },
    ],
  },

  // ── FILES — Upload ────────────────────────────────────────────────────────
  {
    id: 'files-upload',
    group: 'Files — Upload',
    name: 'Upload File',
    method: 'POST',
    baseUrl: 'https://upload.box.com/api/2.0/files/content',
    description: 'Uploads a new file. ⚠ Requires multipart/form-data with "file" part and "attributes" JSON. Max 50 MB — use chunked upload for larger files.',
    params: [
      { key: 'parent.id', type: 'body', required: true, hint: 'e.g. 0', description: 'ID of the destination folder.' },
      { key: 'name',       type: 'body', required: true, hint: 'e.g. report.pdf', description: 'Name for the uploaded file.' },
    ],
  },
  {
    id: 'files-upload-new-version',
    group: 'Files — Upload',
    name: 'Upload New File Version',
    method: 'POST',
    baseUrl: 'https://upload.box.com/api/2.0/files/{file_id}/content',
    description: 'Uploads a new version of an existing file. ⚠ Requires multipart/form-data.',
    params: [
      { key: 'file_id', type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID to update.' },
      { key: 'name',    type: 'body', required: false, hint: 'e.g. report-v2.pdf', description: 'Optional new name for this version.' },
    ],
  },
  {
    id: 'files-chunked-upload-start',
    group: 'Files — Upload',
    name: 'Start Chunked Upload Session',
    method: 'POST',
    baseUrl: 'https://upload.box.com/api/2.0/files/upload_sessions',
    description: 'Starts an upload session for files > 50 MB. Returns a session ID for subsequent chunk uploads.',
    params: [
      { key: 'folder_id',   type: 'body', required: true, hint: 'e.g. 0', description: 'Destination folder ID.' },
      { key: 'file_size',   type: 'body', required: true, hint: 'e.g. 1073741824', description: 'Total file size in bytes.' },
      { key: 'file_name',   type: 'body', required: true, hint: 'e.g. bigfile.zip', description: 'Name for the file.' },
    ],
  },
  {
    id: 'files-chunked-upload-commit',
    group: 'Files — Upload',
    name: 'Commit Chunked Upload Session',
    method: 'POST',
    baseUrl: 'https://upload.box.com/api/2.0/files/upload_sessions/{upload_session_id}/commit',
    description: 'Commits a chunked upload session after all parts have been uploaded.',
    params: [
      { key: 'upload_session_id', type: 'path', required: true, hint: 'e.g. F971964745A5CD0C001BBE4E58196BFD', description: 'Upload session ID.' },
      { key: 'parts',             type: 'body', required: true, hint: 'e.g. [{"part_id":"...", "offset":0, "size":1024, "sha1":"..."}]', description: 'Array of all uploaded parts.' },
    ],
  },
  {
    id: 'files-upload-session-get',
    group: 'Files — Upload',
    name: 'Get Upload Session',
    method: 'GET',
    baseUrl: 'https://upload.box.com/api/2.0/files/upload_sessions/{upload_session_id}',
    description: 'Returns info about an active chunked upload session.',
    params: [
      { key: 'upload_session_id', type: 'path', required: true, hint: 'e.g. F971964745A5CD0C001BBE4E58196BFD', description: 'Upload session ID.' },
    ],
  },
  {
    id: 'files-upload-session-parts',
    group: 'Files — Upload',
    name: 'List Upload Session Parts',
    method: 'GET',
    baseUrl: 'https://upload.box.com/api/2.0/files/upload_sessions/{upload_session_id}/parts',
    description: 'Returns all parts uploaded in a chunked upload session.',
    params: [
      { key: 'upload_session_id', type: 'path', required: true, hint: 'e.g. F971964745A5CD0C001BBE4E58196BFD', description: 'Upload session ID.' },
    ],
  },

  // ── FOLDERS — Read ────────────────────────────────────────────────────────
  {
    id: 'folders-get',
    group: 'Folders — Read',
    name: 'Get Folder Info',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/folders/{folder_id}',
    description: 'Returns metadata for a folder — name, owner, parent, shared link, item count.',
    params: [
      { key: 'folder_id', type: 'path', required: true, hint: 'e.g. 0  (root)  or  184956722927', description: 'Box folder ID. 0 = root.' },
      { key: 'fields',    type: 'query', required: false, hint: 'e.g. name,item_count,owned_by,modified_at', description: 'Fields to include.' },
    ],
  },
  {
    id: 'folders-list-items',
    group: 'Folders — Read',
    name: 'List Folder Items',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/folders/{folder_id}/items',
    description: 'Returns files and sub-folders inside a Box folder.',
    params: [
      { key: 'folder_id',       type: 'path', required: true, hint: 'e.g. 0  (root)  or  184956722927', description: 'Box folder ID. 0 = root.' },
      { key: 'limit',           type: 'query', required: false, hint: 'e.g. 999', description: 'Max items per page.' },
      { key: 'offset',          type: 'query', required: false, hint: 'e.g. 0', description: 'Pagination offset.' },
      { key: 'fields',          type: 'query', required: false, hint: 'e.g. name,id,size,type,created_at,modified_at,owned_by,parent,sha1', description: 'Fields to include in each item.' },
      { key: 'include_deleted', type: 'query', required: false, hint: 'e.g. true', description: 'Include deleted items.' },
      { key: 'sort',            type: 'query', required: false, hint: 'e.g. name', description: 'Sort field: id, name, date, or size.' },
      { key: 'direction',       type: 'query', required: false, hint: 'e.g. ASC', description: 'Sort direction: ASC or DESC.' },
    ],
  },
  {
    id: 'folders-get-collaborations',
    group: 'Folders — Read',
    name: 'List Folder Collaborations',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/folders/{folder_id}/collaborations',
    description: 'Returns all collaborations (permissions) on a folder.',
    params: [
      { key: 'folder_id', type: 'path', required: true, hint: 'e.g. 0', description: 'Box folder ID.' },
      { key: 'fields',    type: 'query', required: false, hint: 'e.g. id,type,accessible_by,role,status', description: 'Fields to include.' },
      { key: 'limit',     type: 'query', required: false, hint: 'e.g. 100', description: 'Max collaborations to return.' },
    ],
  },
  {
    id: 'folders-get-metadata',
    group: 'Folders — Read',
    name: 'List Folder Metadata Instances',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/folders/{folder_id}/metadata',
    description: 'Returns all metadata instances applied to a folder.',
    params: [
      { key: 'folder_id', type: 'path', required: true, hint: 'e.g. 184956722927', description: 'Box folder ID.' },
    ],
  },
  {
    id: 'folders-get-watermark',
    group: 'Folders — Read',
    name: 'Get Folder Watermark',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/folders/{folder_id}/watermark',
    description: 'Returns watermark info for a folder.',
    params: [
      { key: 'folder_id', type: 'path', required: true, hint: 'e.g. 184956722927', description: 'Box folder ID.' },
    ],
  },
  {
    id: 'folders-get-trash',
    group: 'Folders — Read',
    name: 'Get Trashed Folder',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/folders/{folder_id}/trash',
    description: 'Returns metadata about a folder in the trash.',
    params: [
      { key: 'folder_id', type: 'path', required: true, hint: 'e.g. 184956722927', description: 'Box folder ID.' },
    ],
  },
  {
    id: 'folders-get-locks',
    group: 'Folders — Read',
    name: 'List Folder Locks',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/folder_locks',
    description: 'Returns all lock policies on a folder.',
    params: [
      { key: 'folder_id', type: 'query', required: true, hint: 'e.g. 184956722927', description: 'Box folder ID to check locks for.' },
    ],
  },
  {
    id: 'trash-list-items',
    group: 'Folders — Read',
    name: 'List Trashed Items',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/folders/trash/items',
    description: 'Returns all files and folders in the trash.',
    params: [
      { key: 'limit',     type: 'query', required: false, hint: 'e.g. 100', description: 'Max items to return.' },
      { key: 'offset',    type: 'query', required: false, hint: 'e.g. 0', description: 'Pagination offset.' },
      { key: 'fields',    type: 'query', required: false, hint: 'e.g. name,type,size', description: 'Fields to include.' },
      { key: 'sort',      type: 'query', required: false, hint: 'e.g. name', description: 'Sort by: name, date, or size.' },
      { key: 'direction', type: 'query', required: false, hint: 'e.g. ASC', description: 'Sort direction: ASC or DESC.' },
    ],
  },

  // ── FOLDERS — Write ───────────────────────────────────────────────────────
  {
    id: 'folders-create',
    group: 'Folders — Write',
    name: 'Create Folder',
    method: 'POST',
    baseUrl: 'https://api.box.com/2.0/folders',
    description: 'Creates a new folder inside a parent folder.',
    params: [
      { key: 'name',       type: 'body', required: true, hint: 'e.g. New Reports', description: 'Name for the new folder.' },
      { key: 'parent.id', type: 'body', required: true, hint: 'e.g. 0', description: 'Parent folder ID. 0 = root.' },
    ],
  },
  {
    id: 'folders-update',
    group: 'Folders — Write',
    name: 'Update / Rename / Move Folder',
    method: 'PUT',
    baseUrl: 'https://api.box.com/2.0/folders/{folder_id}',
    description: 'Updates a folder — rename it, change its description, or move it to a different parent.',
    params: [
      { key: 'folder_id',   type: 'path', required: true, hint: 'e.g. 184956722927', description: 'Box folder ID.' },
      { key: 'name',         type: 'body', required: false, hint: 'e.g. Renamed Folder', description: 'New name.' },
      { key: 'description',  type: 'body', required: false, hint: 'e.g. Updated folder', description: 'New description.' },
      { key: 'parent.id',   type: 'body', required: false, hint: 'e.g. 0', description: 'New parent folder ID (to move).' },
    ],
  },
  {
    id: 'folders-copy',
    group: 'Folders — Write',
    name: 'Copy Folder',
    method: 'POST',
    baseUrl: 'https://api.box.com/2.0/folders/{folder_id}/copy',
    description: 'Copies a folder and its contents to another location.',
    params: [
      { key: 'folder_id',  type: 'path', required: true, hint: 'e.g. 184956722927', description: 'Box folder ID to copy.' },
      { key: 'parent.id', type: 'body', required: true, hint: 'e.g. 0', description: 'Destination folder ID.' },
      { key: 'name',       type: 'body', required: false, hint: 'e.g. Copy of Reports', description: 'Optional name for the copy.' },
    ],
  },
  {
    id: 'folders-delete',
    group: 'Folders — Write',
    name: 'Delete Folder',
    method: 'DELETE',
    baseUrl: 'https://api.box.com/2.0/folders/{folder_id}',
    description: 'Moves a folder to the trash.',
    params: [
      { key: 'folder_id', type: 'path', required: true, hint: 'e.g. 184956722927', description: 'Box folder ID.' },
      { key: 'recursive', type: 'query', required: false, hint: 'e.g. true', description: 'Set true to delete a non-empty folder.' },
    ],
  },

  // ── USERS ─────────────────────────────────────────────────────────────────
  {
    id: 'users-list',
    group: 'Users',
    name: 'List Users',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/users',
    description: 'Returns all users in the Box enterprise.',
    params: [
      { key: 'fields',        type: 'query', required: false, hint: 'e.g. name,role,login,space_used,space_amount,status', description: 'Comma-separated fields.' },
      { key: 'limit',         type: 'query', required: false, hint: 'e.g. 999', description: 'Max users per page.' },
      { key: 'offset',        type: 'query', required: false, hint: 'e.g. 0', description: 'Pagination offset.' },
      { key: 'filter_term',   type: 'query', required: false, hint: 'e.g. john', description: 'Filter by name or login containing this string.' },
      { key: 'user_type',     type: 'query', required: false, hint: 'e.g. all', description: 'Filter: all, external, or managed.' },
    ],
  },
  {
    id: 'users-get-me',
    group: 'Users',
    name: 'Get Current User (Me)',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/users/me',
    description: 'Returns the profile of the currently authenticated user.',
    params: [
      { key: 'fields', type: 'query', required: false, hint: 'e.g. id,name,login,space_used,space_amount,status', description: 'Fields to include.' },
    ],
  },
  {
    id: 'users-get',
    group: 'Users',
    name: 'Get User Details',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/users/{user_id}',
    description: 'Returns full details for a specific Box user — role, status, storage, etc.',
    params: [
      { key: 'user_id', type: 'path', required: true, hint: 'e.g. 18847114713', description: 'Box user ID (numeric).' },
      { key: 'fields',  type: 'query', required: false, hint: 'e.g. id,name,login,role,status,space_used,space_amount', description: 'Fields to include.' },
    ],
  },
  {
    id: 'users-get-avatar',
    group: 'Users',
    name: 'Get User Avatar',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/users/{user_id}/avatar',
    description: 'Returns the profile image of a Box user.',
    params: [
      { key: 'user_id', type: 'path', required: true, hint: 'e.g. 18847114713', description: 'Box user ID.' },
    ],
  },
  {
    id: 'users-get-email-aliases',
    group: 'Users',
    name: 'List User Email Aliases',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/users/{user_id}/email_aliases',
    description: 'Returns all email aliases for a Box user.',
    params: [
      { key: 'user_id', type: 'path', required: true, hint: 'e.g. 18847114713', description: 'Box user ID.' },
    ],
  },
  {
    id: 'users-get-memberships',
    group: 'Users',
    name: 'List User Group Memberships',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/users/{user_id}/memberships',
    description: 'Returns all groups a user belongs to.',
    params: [
      { key: 'user_id', type: 'path', required: true, hint: 'e.g. 18847114713', description: 'Box user ID.' },
      { key: 'limit',   type: 'query', required: false, hint: 'e.g. 100', description: 'Max memberships to return.' },
      { key: 'offset',  type: 'query', required: false, hint: 'e.g. 0', description: 'Pagination offset.' },
    ],
  },
  {
    id: 'users-create',
    group: 'Users',
    name: 'Create User',
    method: 'POST',
    baseUrl: 'https://api.box.com/2.0/users',
    description: 'Creates a new Box user in the enterprise.',
    params: [
      { key: 'login',      type: 'body', required: true, hint: 'e.g. john.doe@company.com', description: 'Email address (used as login).' },
      { key: 'name',       type: 'body', required: true, hint: 'e.g. John Doe', description: 'Full display name.' },
      { key: 'role',       type: 'body', required: false, hint: 'e.g. user', description: 'Role: user, coadmin, or admin.' },
      { key: 'space_amount', type: 'body', required: false, hint: 'e.g. 10737418240', description: 'Storage quota in bytes (-1 = unlimited).' },
    ],
  },
  {
    id: 'users-update',
    group: 'Users',
    name: 'Update User',
    method: 'PUT',
    baseUrl: 'https://api.box.com/2.0/users/{user_id}',
    description: 'Updates a Box user — name, role, status, storage limit.',
    params: [
      { key: 'user_id',     type: 'path', required: true, hint: 'e.g. 18847114713', description: 'Box user ID.' },
      { key: 'name',        type: 'body', required: false, hint: 'e.g. Jane Doe', description: 'New display name.' },
      { key: 'role',        type: 'body', required: false, hint: 'e.g. user', description: 'New role: user, coadmin.' },
      { key: 'status',      type: 'body', required: false, hint: 'e.g. inactive', description: 'Status: active or inactive.' },
      { key: 'space_amount',type: 'body', required: false, hint: 'e.g. 10737418240', description: 'Storage quota in bytes.' },
    ],
  },
  {
    id: 'users-delete',
    group: 'Users',
    name: 'Delete User',
    method: 'DELETE',
    baseUrl: 'https://api.box.com/2.0/users/{user_id}',
    description: 'Deletes a Box user. Transfer their content first or set force=true.',
    params: [
      { key: 'user_id',  type: 'path', required: true, hint: 'e.g. 18847114713', description: 'Box user ID.' },
      { key: 'force',    type: 'query', required: false, hint: 'e.g. false', description: 'If true, deletes even if user has content.' },
      { key: 'notify',   type: 'query', required: false, hint: 'e.g. false', description: 'If true, sends a notification email.' },
    ],
  },

  // ── GROUPS ────────────────────────────────────────────────────────────────
  {
    id: 'groups-list',
    group: 'Groups',
    name: 'List Groups',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/groups',
    description: 'Returns all groups in the Box enterprise.',
    params: [
      { key: 'fields',      type: 'query', required: false, hint: 'e.g. id,name,group_type,created_at', description: 'Fields to include.' },
      { key: 'limit',       type: 'query', required: false, hint: 'e.g. 100', description: 'Max groups to return.' },
      { key: 'offset',      type: 'query', required: false, hint: 'e.g. 0', description: 'Pagination offset.' },
      { key: 'filter_term', type: 'query', required: false, hint: 'e.g. Engineering', description: 'Filter groups by name.' },
    ],
  },
  {
    id: 'groups-get',
    group: 'Groups',
    name: 'Get Group',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/groups/{group_id}',
    description: 'Returns details for a specific group.',
    params: [
      { key: 'group_id', type: 'path', required: true, hint: 'e.g. 1786931', description: 'Box group ID.' },
      { key: 'fields',   type: 'query', required: false, hint: 'e.g. id,name,group_type', description: 'Fields to include.' },
    ],
  },
  {
    id: 'groups-get-memberships',
    group: 'Groups',
    name: 'List Group Memberships',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/groups/{group_id}/memberships',
    description: 'Returns all members (users) of a specific group.',
    params: [
      { key: 'group_id', type: 'path', required: true, hint: 'e.g. 1786931', description: 'Box group ID.' },
      { key: 'limit',    type: 'query', required: false, hint: 'e.g. 100', description: 'Max members to return.' },
      { key: 'offset',   type: 'query', required: false, hint: 'e.g. 0', description: 'Pagination offset.' },
    ],
  },
  {
    id: 'groups-get-collaborations',
    group: 'Groups',
    name: 'List Group Collaborations',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/groups/{group_id}/collaborations',
    description: 'Returns all folder/file collaborations for a group.',
    params: [
      { key: 'group_id', type: 'path', required: true, hint: 'e.g. 1786931', description: 'Box group ID.' },
      { key: 'fields',   type: 'query', required: false, hint: 'e.g. id,item,role', description: 'Fields to include.' },
    ],
  },
  {
    id: 'groups-create',
    group: 'Groups',
    name: 'Create Group',
    method: 'POST',
    baseUrl: 'https://api.box.com/2.0/groups',
    description: 'Creates a new group in the Box enterprise.',
    params: [
      { key: 'name',        type: 'body', required: true, hint: 'e.g. Engineering Team', description: 'Group name.' },
      { key: 'description', type: 'body', required: false, hint: 'e.g. All engineers', description: 'Group description.' },
    ],
  },
  {
    id: 'group-memberships-create',
    group: 'Groups',
    name: 'Add User to Group',
    method: 'POST',
    baseUrl: 'https://api.box.com/2.0/group_memberships',
    description: 'Adds a user to a group.',
    params: [
      { key: 'user.id',  type: 'body', required: true, hint: 'e.g. 18847114713', description: 'Box user ID.' },
      { key: 'group.id', type: 'body', required: true, hint: 'e.g. 1786931', description: 'Box group ID.' },
      { key: 'role',     type: 'body', required: false, hint: 'e.g. member', description: 'Role: member or admin.' },
    ],
  },
  {
    id: 'group-memberships-delete',
    group: 'Groups',
    name: 'Remove User from Group',
    method: 'DELETE',
    baseUrl: 'https://api.box.com/2.0/group_memberships/{membership_id}',
    description: 'Removes a user from a group.',
    params: [
      { key: 'membership_id', type: 'path', required: true, hint: 'e.g. 1560354', description: 'Group membership ID.' },
    ],
  },

  // ── COLLABORATIONS ────────────────────────────────────────────────────────
  {
    id: 'collaborations-get',
    group: 'Collaborations',
    name: 'Get Collaboration',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/collaborations/{collaboration_id}',
    description: 'Returns details of a specific collaboration.',
    params: [
      { key: 'collaboration_id', type: 'path', required: true, hint: 'e.g. 791293', description: 'Collaboration ID.' },
      { key: 'fields', type: 'query', required: false, hint: 'e.g. id,type,accessible_by,item,role,status', description: 'Fields to include.' },
    ],
  },
  {
    id: 'collaborations-list-pending',
    group: 'Collaborations',
    name: 'List Pending Collaborations',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/collaborations',
    description: 'Returns all pending collaboration invitations for the current user.',
    params: [
      { key: 'status', type: 'query', required: true, hint: 'e.g. pending', description: 'Filter by status: pending.' },
      { key: 'fields', type: 'query', required: false, hint: 'e.g. id,item,role,accessible_by', description: 'Fields to include.' },
    ],
  },
  {
    id: 'collaborations-create',
    group: 'Collaborations',
    name: 'Create Collaboration (Share)',
    method: 'POST',
    baseUrl: 'https://api.box.com/2.0/collaborations',
    description: 'Adds a collaborator (user or group) to a file or folder.',
    params: [
      { key: 'item.id',           type: 'body', required: true, hint: 'e.g. 184956722927', description: 'File or folder ID to share.' },
      { key: 'item.type',         type: 'body', required: true, hint: 'e.g. folder', description: 'folder or file.' },
      { key: 'accessible_by.id',  type: 'body', required: false, hint: 'e.g. 18847114713', description: 'User or group ID to add.' },
      { key: 'accessible_by.type',type: 'body', required: false, hint: 'e.g. user', description: 'user or group.' },
      { key: 'accessible_by.login',type: 'body', required: false, hint: 'e.g. user@example.com', description: 'Email (for external users).' },
      { key: 'role',              type: 'body', required: true, hint: 'e.g. viewer', description: 'editor, viewer, previewer, uploader, previewer uploader, viewer uploader, co-owner.' },
    ],
  },
  {
    id: 'collaborations-update',
    group: 'Collaborations',
    name: 'Update Collaboration Role',
    method: 'PUT',
    baseUrl: 'https://api.box.com/2.0/collaborations/{collaboration_id}',
    description: 'Updates the role or status of a collaboration.',
    params: [
      { key: 'collaboration_id', type: 'path', required: true, hint: 'e.g. 791293', description: 'Collaboration ID.' },
      { key: 'role',             type: 'body', required: false, hint: 'e.g. editor', description: 'New role.' },
      { key: 'status',           type: 'body', required: false, hint: 'e.g. accepted', description: 'New status: accepted or rejected.' },
    ],
  },
  {
    id: 'collaborations-delete',
    group: 'Collaborations',
    name: 'Delete Collaboration',
    method: 'DELETE',
    baseUrl: 'https://api.box.com/2.0/collaborations/{collaboration_id}',
    description: 'Removes a collaboration — revokes access for the collaborator.',
    params: [
      { key: 'collaboration_id', type: 'path', required: true, hint: 'e.g. 791293', description: 'Collaboration ID to remove.' },
    ],
  },

  // ── SHARED LINKS ──────────────────────────────────────────────────────────
  {
    id: 'shared-items-get',
    group: 'Shared Links',
    name: 'Get Shared Link Item Info',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/shared_items',
    description: 'Returns the file or folder associated with a shared link URL.',
    params: [
      { key: 'fields', type: 'query', required: false, hint: 'e.g. id,name,type,size', description: 'Fields to include.' },
    ],
  },
  {
    id: 'files-add-shared-link',
    group: 'Shared Links',
    name: 'Create/Update File Shared Link',
    method: 'PUT',
    baseUrl: 'https://api.box.com/2.0/files/{file_id}?operation=add_shared_link',
    description: 'Creates or updates a shared link for a file.',
    params: [
      { key: 'file_id',                     type: 'path', required: true, hint: 'e.g. 699581512549', description: 'Box file ID.' },
      { key: 'shared_link.access',           type: 'body', required: false, hint: 'e.g. open', description: 'Link access: open, company, or collaborators.' },
      { key: 'shared_link.password',         type: 'body', required: false, hint: 'e.g. mypassword', description: 'Password to protect the link.' },
      { key: 'shared_link.unshared_at',      type: 'body', required: false, hint: 'e.g. 2025-12-31T00:00:00Z', description: 'Expiration date (ISO 8601).' },
      { key: 'shared_link.permissions.can_download', type: 'body', required: false, hint: 'e.g. true', description: 'Allow download via the link.' },
    ],
  },
  {
    id: 'folders-add-shared-link',
    group: 'Shared Links',
    name: 'Create/Update Folder Shared Link',
    method: 'PUT',
    baseUrl: 'https://api.box.com/2.0/folders/{folder_id}?operation=add_shared_link',
    description: 'Creates or updates a shared link for a folder.',
    params: [
      { key: 'folder_id',                   type: 'path', required: true, hint: 'e.g. 184956722927', description: 'Box folder ID.' },
      { key: 'shared_link.access',           type: 'body', required: false, hint: 'e.g. open', description: 'Link access: open, company, or collaborators.' },
      { key: 'shared_link.unshared_at',      type: 'body', required: false, hint: 'e.g. 2025-12-31T00:00:00Z', description: 'Expiration date.' },
      { key: 'shared_link.permissions.can_download', type: 'body', required: false, hint: 'e.g. true', description: 'Allow download.' },
    ],
  },

  // ── SEARCH ────────────────────────────────────────────────────────────────
  {
    id: 'search',
    group: 'Search',
    name: 'Search',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/search',
    description: 'Searches for files, folders, and web links matching a query.',
    params: [
      { key: 'query',           type: 'query', required: true, hint: 'e.g. invoice 2024', description: 'The search query string.' },
      { key: 'type',            type: 'query', required: false, hint: 'e.g. file', description: 'Filter by type: file, folder, or web_link.' },
      { key: 'fields',          type: 'query', required: false, hint: 'e.g. name,id,size,type,modified_at', description: 'Fields to return.' },
      { key: 'limit',           type: 'query', required: false, hint: 'e.g. 100', description: 'Max results (max 200).' },
      { key: 'offset',          type: 'query', required: false, hint: 'e.g. 0', description: 'Pagination offset.' },
      { key: 'ancestor_folder_ids', type: 'query', required: false, hint: 'e.g. 184956722927', description: 'Restrict to a specific folder.' },
      { key: 'content_types',   type: 'query', required: false, hint: 'e.g. name', description: 'Search in: name, description, file_content, comments.' },
    ],
  },

  // ── EVENTS ────────────────────────────────────────────────────────────────
  {
    id: 'events-get',
    group: 'Events',
    name: 'Get Events',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/events',
    description: 'Returns events for the current user or the entire enterprise.',
    params: [
      { key: 'stream_type',    type: 'query', required: false, hint: 'e.g. changes', description: 'Stream type: changes, all, admin_logs, or admin_logs_streaming.' },
      { key: 'limit',          type: 'query', required: false, hint: 'e.g. 500', description: 'Max events to return.' },
      { key: 'stream_position',type: 'query', required: false, hint: 'e.g. now', description: 'Position in event stream. Use now for latest.' },
      { key: 'event_type',     type: 'query', required: false, hint: 'e.g. UPLOAD,DOWNLOAD', description: 'Filter by event type(s).' },
    ],
  },

  // ── TASKS ─────────────────────────────────────────────────────────────────
  {
    id: 'tasks-get',
    group: 'Tasks',
    name: 'Get Task',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/tasks/{task_id}',
    description: 'Returns details of a specific task.',
    params: [
      { key: 'task_id', type: 'path', required: true, hint: 'e.g. 12345', description: 'Box task ID.' },
    ],
  },
  {
    id: 'tasks-get-assignments',
    group: 'Tasks',
    name: 'List Task Assignments',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/tasks/{task_id}/assignments',
    description: 'Returns all assignments for a task.',
    params: [
      { key: 'task_id', type: 'path', required: true, hint: 'e.g. 12345', description: 'Box task ID.' },
    ],
  },
  {
    id: 'tasks-create',
    group: 'Tasks',
    name: 'Create Task',
    method: 'POST',
    baseUrl: 'https://api.box.com/2.0/tasks',
    description: 'Creates a task on a file.',
    params: [
      { key: 'item.id',   type: 'body', required: true, hint: 'e.g. 699581512549', description: 'File ID to assign task to.' },
      { key: 'item.type', type: 'body', required: true, hint: 'e.g. file', description: 'Must be file.' },
      { key: 'message',   type: 'body', required: false, hint: 'e.g. Please review', description: 'Task message/instructions.' },
      { key: 'due_at',    type: 'body', required: false, hint: 'e.g. 2025-12-31T00:00:00Z', description: 'Due date (ISO 8601).' },
      { key: 'action',    type: 'body', required: false, hint: 'e.g. review', description: 'review or complete.' },
    ],
  },

  // ── METADATA TEMPLATES ────────────────────────────────────────────────────
  {
    id: 'metadata-templates-list-enterprise',
    group: 'Metadata',
    name: 'List Enterprise Metadata Templates',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/metadata_templates/enterprise',
    description: 'Returns all metadata templates defined for the enterprise.',
    params: [
      { key: 'limit',  type: 'query', required: false, hint: 'e.g. 100', description: 'Max templates to return.' },
      { key: 'marker', type: 'query', required: false, hint: 'e.g. <marker from previous response>', description: 'For pagination.' },
    ],
  },
  {
    id: 'metadata-templates-get',
    group: 'Metadata',
    name: 'Get Metadata Template Schema',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/metadata_templates/{scope}/{template_key}/schema',
    description: 'Returns the schema (field definitions) for a metadata template.',
    params: [
      { key: 'scope',        type: 'path', required: true, hint: 'e.g. enterprise', description: 'Template scope: enterprise or global.' },
      { key: 'template_key', type: 'path', required: true, hint: 'e.g. employeeRecord', description: 'The template key.' },
    ],
  },
  {
    id: 'metadata-query-execute',
    group: 'Metadata',
    name: 'Execute Metadata Query',
    method: 'POST',
    baseUrl: 'https://api.box.com/2.0/metadata_queries/execute_read',
    description: 'Searches for files and folders using a metadata template query.',
    params: [
      { key: 'from',          type: 'body', required: true, hint: 'e.g. enterprise_123456.myTemplate', description: 'Metadata template scope.key.' },
      { key: 'query',         type: 'body', required: false, hint: 'e.g. amount >= :min', description: 'Query string with placeholders.' },
      { key: 'query_params',  type: 'body', required: false, hint: 'e.g. {"min": 100}', description: 'Values for query placeholders.' },
      { key: 'ancestor_folder_id', type: 'body', required: true, hint: 'e.g. 0', description: 'Folder to search within.' },
      { key: 'fields',        type: 'body', required: false, hint: 'e.g. ["name","metadata.enterprise_12345.myTemplate.amount"]', description: 'Fields to return.' },
    ],
  },

  // ── WEBHOOKS ──────────────────────────────────────────────────────────────
  {
    id: 'webhooks-list',
    group: 'Webhooks',
    name: 'List Webhooks',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/webhooks',
    description: 'Returns all webhooks configured for the current application.',
    params: [
      { key: 'limit',  type: 'query', required: false, hint: 'e.g. 100', description: 'Max webhooks to return.' },
      { key: 'marker', type: 'query', required: false, hint: 'e.g. <marker from previous response>', description: 'For pagination.' },
    ],
  },
  {
    id: 'webhooks-get',
    group: 'Webhooks',
    name: 'Get Webhook',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/webhooks/{webhook_id}',
    description: 'Returns details of a specific webhook.',
    params: [
      { key: 'webhook_id', type: 'path', required: true, hint: 'e.g. 12345', description: 'Webhook ID.' },
    ],
  },
  {
    id: 'webhooks-create',
    group: 'Webhooks',
    name: 'Create Webhook',
    method: 'POST',
    baseUrl: 'https://api.box.com/2.0/webhooks',
    description: 'Creates a webhook that fires when events occur on a file or folder.',
    params: [
      { key: 'target.id',   type: 'body', required: true, hint: 'e.g. 184956722927', description: 'ID of file or folder to watch.' },
      { key: 'target.type', type: 'body', required: true, hint: 'e.g. folder', description: 'file or folder.' },
      { key: 'address',     type: 'body', required: true, hint: 'e.g. https://yourserver.com/webhook', description: 'URL to receive webhook events.' },
      { key: 'triggers',    type: 'body', required: true, hint: 'e.g. ["FILE.UPLOADED","FILE.DELETED"]', description: 'Array of event trigger names.' },
    ],
  },

  // ── LEGAL HOLD ────────────────────────────────────────────────────────────
  {
    id: 'legal-hold-policies-list',
    group: 'Legal Hold',
    name: 'List Legal Hold Policies',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/legal_hold_policies',
    description: 'Returns all legal hold policies in the enterprise.',
    params: [
      { key: 'policy_name', type: 'query', required: false, hint: 'e.g. GDPR Hold', description: 'Filter by policy name.' },
      { key: 'limit',       type: 'query', required: false, hint: 'e.g. 100', description: 'Max policies to return.' },
    ],
  },
  {
    id: 'legal-hold-policies-get',
    group: 'Legal Hold',
    name: 'Get Legal Hold Policy',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/legal_hold_policies/{policy_id}',
    description: 'Returns details of a specific legal hold policy.',
    params: [
      { key: 'policy_id', type: 'path', required: true, hint: 'e.g. 12345', description: 'Legal hold policy ID.' },
    ],
  },
  {
    id: 'legal-hold-assignments-list',
    group: 'Legal Hold',
    name: 'List Legal Hold Assignments',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/legal_hold_policy_assignments',
    description: 'Returns all items assigned to a legal hold policy.',
    params: [
      { key: 'policy_id', type: 'query', required: true, hint: 'e.g. 12345', description: 'Legal hold policy ID.' },
      { key: 'assign_to_type', type: 'query', required: false, hint: 'e.g. folder', description: 'Filter by type: file, folder, or user.' },
      { key: 'limit',     type: 'query', required: false, hint: 'e.g. 100', description: 'Max assignments to return.' },
    ],
  },

  // ── RETENTION POLICIES ────────────────────────────────────────────────────
  {
    id: 'retention-policies-list',
    group: 'Retention Policies',
    name: 'List Retention Policies',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/retention_policies',
    description: 'Returns all retention policies in the enterprise.',
    params: [
      { key: 'policy_name', type: 'query', required: false, hint: 'e.g. 7-year hold', description: 'Filter by policy name.' },
      { key: 'policy_type', type: 'query', required: false, hint: 'e.g. finite', description: 'finite or indefinite.' },
      { key: 'limit',       type: 'query', required: false, hint: 'e.g. 100', description: 'Max policies to return.' },
    ],
  },
  {
    id: 'retention-policies-get',
    group: 'Retention Policies',
    name: 'Get Retention Policy',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/retention_policies/{retention_policy_id}',
    description: 'Returns details of a specific retention policy.',
    params: [
      { key: 'retention_policy_id', type: 'path', required: true, hint: 'e.g. 12345', description: 'Retention policy ID.' },
    ],
  },

  // ── SIGN REQUESTS ─────────────────────────────────────────────────────────
  {
    id: 'sign-requests-list',
    group: 'Sign Requests',
    name: 'List Sign Requests',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/sign_requests',
    description: 'Returns all Box Sign signature requests.',
    params: [
      { key: 'limit',  type: 'query', required: false, hint: 'e.g. 100', description: 'Max sign requests to return.' },
      { key: 'marker', type: 'query', required: false, hint: 'e.g. <marker from previous response>', description: 'For pagination.' },
    ],
  },
  {
    id: 'sign-requests-get',
    group: 'Sign Requests',
    name: 'Get Sign Request',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/sign_requests/{sign_request_id}',
    description: 'Returns details and status of a specific signature request.',
    params: [
      { key: 'sign_request_id', type: 'path', required: true, hint: 'e.g. 42d6a3ba-a0d6-4878-bd02-cb5245a39bc3', description: 'Sign request ID.' },
    ],
  },
  {
    id: 'sign-templates-list',
    group: 'Sign Requests',
    name: 'List Sign Templates',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/sign_templates',
    description: 'Returns all Box Sign templates.',
    params: [
      { key: 'limit',  type: 'query', required: false, hint: 'e.g. 100', description: 'Max templates to return.' },
      { key: 'marker', type: 'query', required: false, hint: 'e.g. <marker from previous response>', description: 'For pagination.' },
    ],
  },

  // ── RECENT ITEMS ──────────────────────────────────────────────────────────
  {
    id: 'recent-items',
    group: 'Recent Items',
    name: 'List Recent Items',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/recent_items',
    description: 'Returns files and folders the current user has recently accessed.',
    params: [
      { key: 'limit',  type: 'query', required: false, hint: 'e.g. 100', description: 'Max items to return.' },
      { key: 'fields', type: 'query', required: false, hint: 'e.g. id,name,type,interacted_at', description: 'Fields to include.' },
    ],
  },

  // ── COLLECTIONS ───────────────────────────────────────────────────────────
  {
    id: 'collections-list',
    group: 'Collections',
    name: 'List Collections',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/collections',
    description: 'Returns all collections for the current user (e.g. Favorites).',
    params: [],
  },
  {
    id: 'collections-get-items',
    group: 'Collections',
    name: 'List Collection Items',
    method: 'GET',
    baseUrl: 'https://api.box.com/2.0/collections/{collection_id}/items',
    description: 'Returns all files and folders in a collection.',
    params: [
      { key: 'collection_id', type: 'path', required: true, hint: 'e.g. 926489', description: 'Collection ID (get from List Collections).' },
      { key: 'fields',        type: 'query', required: false, hint: 'e.g. id,name,type,size', description: 'Fields to include.' },
      { key: 'limit',         type: 'query', required: false, hint: 'e.g. 100', description: 'Max items to return.' },
      { key: 'offset',        type: 'query', required: false, hint: 'e.g. 0', description: 'Pagination offset.' },
    ],
  },
];
