// All Dropbox HTTP API v2 endpoints
// Source: https://www.dropbox.com/developers/documentation/http/documentation
// Every POST endpoint is included, grouped by namespace.
// Endpoints that require special content-type (upload/download) are noted in their description.

export const dropboxAPIs = [

  // ── FILES — Read ──────────────────────────────────────────────────────────
  {
    id: 'files-get-metadata',
    group: 'Files — Read',
    name: 'Get Metadata',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/get_metadata',
    description: 'Returns the metadata for a file or folder at the given path.',
    params: [
      { key: 'path', type: 'body', required: true,  hint: 'e.g. /Documents/report.pdf', description: 'Full Dropbox path to the file or folder.' },
      { key: 'include_media_info', type: 'body', required: false, hint: 'e.g. false', description: 'Include media info for photos and videos.' },
      { key: 'include_deleted',   type: 'body', required: false, hint: 'e.g. false', description: 'Include deleted items.' },
    ],
  },
  {
    id: 'files-list-folder',
    group: 'Files — Read',
    name: 'List Folder',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/list_folder',
    description: 'Returns the metadata for the contents of a folder.',
    params: [
      { key: 'path',      type: 'body', required: true,  hint: 'e.g. /Documents  (use "" for root)', description: 'Dropbox path to the folder.' },
      { key: 'recursive', type: 'body', required: false, hint: 'e.g. false', description: 'If true, lists all subdirectory contents recursively.' },
      { key: 'limit',     type: 'body', required: false, hint: 'e.g. 100', description: 'Max entries per call (max 2000).' },
      { key: 'include_deleted', type: 'body', required: false, hint: 'e.g. false', description: 'Include deleted entries.' },
      { key: 'include_mounted_folders', type: 'body', required: false, hint: 'e.g. true', description: 'Include mounted shared folders.' },
      { key: 'include_non_downloadable_files', type: 'body', required: false, hint: 'e.g. true', description: 'Include files that cannot be downloaded.' },
    ],
  },
  {
    id: 'files-list-folder-continue',
    group: 'Files — Read',
    name: 'List Folder — Continue (next page)',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/list_folder/continue',
    description: 'Continues listing folder contents from where a previous call left off.',
    params: [
      { key: 'cursor', type: 'body', required: true, hint: 'e.g. <cursor from list_folder response>', description: 'Cursor returned by list_folder or list_folder/continue.' },
    ],
  },
  {
    id: 'files-list-folder-get-latest-cursor',
    group: 'Files — Read',
    name: 'List Folder — Get Latest Cursor',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/list_folder/get_latest_cursor',
    description: 'Gets a cursor for the current state of a folder without returning items. Useful before starting a long-poll.',
    params: [
      { key: 'path',      type: 'body', required: true,  hint: 'e.g. /Documents', description: 'Dropbox path to the folder.' },
      { key: 'recursive', type: 'body', required: false, hint: 'e.g. false', description: 'Match how you plan to poll.' },
    ],
  },
  {
    id: 'files-list-folder-longpoll',
    group: 'Files — Read',
    name: 'List Folder — Long Poll',
    method: 'POST',
    baseUrl: 'https://notify.dropboxapi.com/2/files/list_folder/longpoll',
    description: 'Waits for changes in a folder (long-polling). Use list_folder/continue after this returns.',
    params: [
      { key: 'cursor',  type: 'body', required: true,  hint: 'e.g. <cursor from get_latest_cursor>', description: 'A cursor obtained from list_folder or get_latest_cursor.' },
      { key: 'timeout', type: 'body', required: false, hint: 'e.g. 30', description: 'Max seconds to wait for changes (0–480). Default 30.' },
    ],
  },
  {
    id: 'files-list-revisions',
    group: 'Files — Read',
    name: 'List Revisions',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/list_revisions',
    description: 'Returns the past revisions of a file (up to a limit).',
    params: [
      { key: 'path',  type: 'body', required: true,  hint: 'e.g. /Documents/report.pdf', description: 'Path to the file.' },
      { key: 'limit', type: 'body', required: false, hint: 'e.g. 10', description: 'Max revisions to return (1–100). Default 10.' },
      { key: 'mode',  type: 'body', required: false, hint: 'e.g. path', description: 'path or id. Default path.' },
    ],
  },
  {
    id: 'files-search-v2',
    group: 'Files — Read',
    name: 'Search Files (v2)',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/search_v2',
    description: 'Searches for files and folders that match a query string.',
    params: [
      { key: 'query',              type: 'body', required: true,  hint: 'e.g. invoice 2024', description: 'The search query string.' },
      { key: 'options.path',       type: 'body', required: false, hint: 'e.g. /Documents', description: 'Restrict search to this folder path.' },
      { key: 'options.max_results',type: 'body', required: false, hint: 'e.g. 20', description: 'Max results (1–1000).' },
      { key: 'options.file_status',type: 'body', required: false, hint: 'e.g. active', description: 'active or deleted.' },
    ],
  },
  {
    id: 'files-search-continue-v2',
    group: 'Files — Read',
    name: 'Search — Continue (next page)',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/search/continue_v2',
    description: 'Fetches the next page of search results.',
    params: [
      { key: 'cursor', type: 'body', required: true, hint: 'e.g. <cursor from search_v2 response>', description: 'Cursor from the previous search_v2 response.' },
    ],
  },
  {
    id: 'files-get-temporary-link',
    group: 'Files — Read',
    name: 'Get Temporary Download Link',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/get_temporary_link',
    description: 'Gets a temporary URL that can be used to stream/download a file without needing an access token.',
    params: [
      { key: 'path', type: 'body', required: true, hint: 'e.g. /Videos/intro.mp4', description: 'Full Dropbox path to the file.' },
    ],
  },
  {
    id: 'files-get-temporary-upload-link',
    group: 'Files — Read',
    name: 'Get Temporary Upload Link',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/get_temporary_upload_link',
    description: 'Gets a URL that can be used to upload a file without an access token.',
    params: [
      { key: 'commit_info.path',       type: 'body', required: true, hint: 'e.g. /uploads/file.csv', description: 'Dropbox path where file will be saved.' },
      { key: 'commit_info.mode',       type: 'body', required: false, hint: 'e.g. add', description: 'add, overwrite, or update.' },
      { key: 'duration',               type: 'body', required: false, hint: 'e.g. 14400', description: 'Link validity in seconds (max 14400).' },
    ],
  },
  {
    id: 'files-tag-get',
    group: 'Files — Read',
    name: 'Get Tags',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/tags/get',
    description: 'Returns all tags assigned to a list of files or folders.',
    params: [
      { key: 'paths', type: 'body', required: true, hint: 'e.g. ["/Documents/report.pdf"]', description: 'Array of Dropbox paths to get tags for.' },
    ],
  },
  {
    id: 'files-save-url-check',
    group: 'Files — Read',
    name: 'Save URL — Check Job Status',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/save_url/check_job_status',
    description: 'Checks the status of a save_url job.',
    params: [
      { key: 'async_job_id', type: 'body', required: true, hint: 'e.g. <async_job_id from save_url>', description: 'The job ID returned by save_url.' },
    ],
  },

  // ── FILES — Write ─────────────────────────────────────────────────────────
  {
    id: 'files-copy-v2',
    group: 'Files — Write',
    name: 'Copy File/Folder',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/copy_v2',
    description: 'Copies a file or folder from one location to another in Dropbox.',
    params: [
      { key: 'from_path', type: 'body', required: true, hint: 'e.g. /Documents/old.pdf', description: 'Path of the file/folder to copy.' },
      { key: 'to_path',   type: 'body', required: true, hint: 'e.g. /Archive/old.pdf',   description: 'Destination path.' },
      { key: 'allow_ownership_transfer', type: 'body', required: false, hint: 'e.g. false', description: 'Allow cross-owner copies.' },
    ],
  },
  {
    id: 'files-copy-batch-check-v2',
    group: 'Files — Write',
    name: 'Copy Batch — Check Status',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/copy_batch/check_v2',
    description: 'Returns the status of an asynchronous copy_batch job.',
    params: [
      { key: 'async_job_id', type: 'body', required: true, hint: 'e.g. <async_job_id from copy_batch>', description: 'Job ID from copy_batch.' },
    ],
  },
  {
    id: 'files-create-folder-v2',
    group: 'Files — Write',
    name: 'Create Folder',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/create_folder_v2',
    description: 'Creates a new folder at the given path.',
    params: [
      { key: 'path',         type: 'body', required: true,  hint: 'e.g. /Projects/New Folder', description: 'Full path of the folder to create.' },
      { key: 'autorename',   type: 'body', required: false, hint: 'e.g. false', description: 'If true, auto-renames on conflict.' },
    ],
  },
  {
    id: 'files-create-folder-batch',
    group: 'Files — Write',
    name: 'Create Folder Batch',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/create_folder_batch',
    description: 'Creates multiple folders in one call.',
    params: [
      { key: 'paths',      type: 'body', required: true,  hint: 'e.g. ["/Folder1", "/Folder2"]', description: 'Array of paths to create.' },
      { key: 'autorename', type: 'body', required: false, hint: 'e.g. false', description: 'Auto-rename on conflicts.' },
      { key: 'force_async',type: 'body', required: false, hint: 'e.g. false', description: 'Force async even for small batches.' },
    ],
  },
  {
    id: 'files-delete-v2',
    group: 'Files — Write',
    name: 'Delete File/Folder',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/delete_v2',
    description: 'Deletes a file or folder. For folders, deletes all contents.',
    params: [
      { key: 'path', type: 'body', required: true, hint: 'e.g. /old-file.pdf', description: 'Full Dropbox path to delete.' },
    ],
  },
  {
    id: 'files-permanently-delete',
    group: 'Files — Write',
    name: 'Permanently Delete',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/permanently_delete',
    description: 'Permanently deletes a file or folder (bypasses Dropbox trash). Requires Business plan.',
    params: [
      { key: 'path', type: 'body', required: true, hint: 'e.g. /sensitive/file.pdf', description: 'Full Dropbox path to permanently delete.' },
    ],
  },
  {
    id: 'files-move-v2',
    group: 'Files — Write',
    name: 'Move File/Folder',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/move_v2',
    description: 'Moves a file or folder to a different location in Dropbox.',
    params: [
      { key: 'from_path',  type: 'body', required: true, hint: 'e.g. /old/location.pdf', description: 'Current path.' },
      { key: 'to_path',    type: 'body', required: true, hint: 'e.g. /new/location.pdf', description: 'Destination path.' },
      { key: 'autorename', type: 'body', required: false, hint: 'e.g. false', description: 'Auto-rename on conflict.' },
      { key: 'allow_ownership_transfer', type: 'body', required: false, hint: 'e.g. false', description: 'Allow cross-owner moves.' },
    ],
  },
  {
    id: 'files-restore',
    group: 'Files — Write',
    name: 'Restore File Revision',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/restore',
    description: 'Restores a file to a specific revision.',
    params: [
      { key: 'path', type: 'body', required: true, hint: 'e.g. /Documents/report.pdf', description: 'Path to the file to restore.' },
      { key: 'rev',  type: 'body', required: true, hint: 'e.g. a1c2b3d4e5f6', description: 'Revision string from list_revisions.' },
    ],
  },
  {
    id: 'files-save-url',
    group: 'Files — Write',
    name: 'Save from URL',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/save_url',
    description: 'Saves a file to Dropbox by downloading it from a given URL.',
    params: [
      { key: 'path', type: 'body', required: true, hint: 'e.g. /Downloads/file.pdf', description: 'Dropbox path to save the file to.' },
      { key: 'url',  type: 'body', required: true, hint: 'e.g. https://example.com/file.pdf', description: 'URL to download from.' },
    ],
  },
  {
    id: 'files-lock-file-batch',
    group: 'Files — Write',
    name: 'Lock Files',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/lock_file_batch',
    description: 'Locks files so other users cannot edit them.',
    params: [
      { key: 'entries', type: 'body', required: true, hint: 'e.g. [{"path": "/file.docx"}]', description: 'Array of entries with path to lock.' },
    ],
  },
  {
    id: 'files-unlock-file-batch',
    group: 'Files — Write',
    name: 'Unlock Files',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/unlock_file_batch',
    description: 'Unlocks previously locked files.',
    params: [
      { key: 'entries', type: 'body', required: true, hint: 'e.g. [{"path": "/file.docx"}]', description: 'Array of entries with path to unlock.' },
    ],
  },
  {
    id: 'files-tag-add',
    group: 'Files — Write',
    name: 'Add Tag',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/tags/add',
    description: 'Adds a tag to a file or folder.',
    params: [
      { key: 'path',       type: 'body', required: true, hint: 'e.g. /Documents/report.pdf', description: 'Dropbox path.' },
      { key: 'tag_text',   type: 'body', required: true, hint: 'e.g. important', description: 'The tag string to add.' },
    ],
  },
  {
    id: 'files-tag-remove',
    group: 'Files — Write',
    name: 'Remove Tag',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/files/tags/remove',
    description: 'Removes a tag from a file or folder.',
    params: [
      { key: 'path',     type: 'body', required: true, hint: 'e.g. /Documents/report.pdf', description: 'Dropbox path.' },
      { key: 'tag_text', type: 'body', required: true, hint: 'e.g. important', description: 'The tag to remove.' },
    ],
  },

  // ── FILES — Upload / Download (special) ───────────────────────────────────
  {
    id: 'files-download',
    group: 'Files — Upload/Download',
    name: 'Download File',
    method: 'POST',
    baseUrl: 'https://content.dropboxapi.com/2/files/download',
    description: 'Downloads a file. ⚠ Requires special header: Dropbox-API-Arg: {"path":"/file.pdf"}. Content-Type must be empty. Use Get Temporary Link instead for browser use.',
    params: [
      { key: 'path', type: 'body', required: true, hint: 'e.g. /Documents/report.pdf', description: 'Dropbox path to download. Sent via Dropbox-API-Arg header, not body.' },
    ],
  },
  {
    id: 'files-download-zip',
    group: 'Files — Upload/Download',
    name: 'Download Folder as ZIP',
    method: 'POST',
    baseUrl: 'https://content.dropboxapi.com/2/files/download_zip',
    description: 'Downloads an entire folder as a ZIP archive. ⚠ Requires special header: Dropbox-API-Arg: {"path":"/folder"}.',
    params: [
      { key: 'path', type: 'body', required: true, hint: 'e.g. /Documents', description: 'Path to the folder to zip and download.' },
    ],
  },
  {
    id: 'files-export',
    group: 'Files — Upload/Download',
    name: 'Export File (Dropbox Paper → PDF/etc.)',
    method: 'POST',
    baseUrl: 'https://content.dropboxapi.com/2/files/export',
    description: 'Exports a Dropbox Paper doc or Google Workspace file to a standard format (PDF, DOCX, etc.).',
    params: [
      { key: 'path',         type: 'body', required: true,  hint: 'e.g. /Notes/Meeting.paper', description: 'Path to the file to export.' },
      { key: 'export_format',type: 'body', required: false, hint: 'e.g. pdf', description: 'Export format (pdf, html, docx, etc.).' },
    ],
  },
  {
    id: 'files-upload',
    group: 'Files — Upload/Download',
    name: 'Upload File',
    method: 'POST',
    baseUrl: 'https://content.dropboxapi.com/2/files/upload',
    description: 'Uploads a file. ⚠ Requires Content-Type: application/octet-stream and Dropbox-API-Arg header. Max 150 MB — use upload sessions for larger files.',
    params: [
      { key: 'path',       type: 'body', required: true,  hint: 'e.g. /uploads/data.csv', description: 'Dropbox path where file will be saved.' },
      { key: 'mode',       type: 'body', required: false, hint: 'e.g. add', description: 'add, overwrite, or update.' },
      { key: 'autorename', type: 'body', required: false, hint: 'e.g. false', description: 'Auto-rename if file already exists.' },
    ],
  },
  {
    id: 'files-upload-session-start',
    group: 'Files — Upload/Download',
    name: 'Upload Session — Start',
    method: 'POST',
    baseUrl: 'https://content.dropboxapi.com/2/files/upload_session/start',
    description: 'Starts an upload session for files larger than 150 MB.',
    params: [
      { key: 'close', type: 'body', required: false, hint: 'e.g. false', description: 'If true, close the session after this call.' },
    ],
  },
  {
    id: 'files-upload-session-finish',
    group: 'Files — Upload/Download',
    name: 'Upload Session — Finish',
    method: 'POST',
    baseUrl: 'https://content.dropboxapi.com/2/files/upload_session/finish',
    description: 'Finishes an upload session and saves the file.',
    params: [
      { key: 'cursor.session_id', type: 'body', required: true, hint: 'e.g. <session_id from start>', description: 'Session ID from upload_session/start.' },
      { key: 'cursor.offset',     type: 'body', required: true, hint: 'e.g. 0', description: 'Total bytes uploaded so far.' },
      { key: 'commit.path',       type: 'body', required: true, hint: 'e.g. /uploads/bigfile.zip', description: 'Final Dropbox path for the file.' },
      { key: 'commit.mode',       type: 'body', required: false, hint: 'e.g. add', description: 'add, overwrite, or update.' },
    ],
  },
  {
    id: 'files-get-thumbnail-v2',
    group: 'Files — Upload/Download',
    name: 'Get Thumbnail',
    method: 'POST',
    baseUrl: 'https://content.dropboxapi.com/2/files/get_thumbnail_v2',
    description: 'Gets a thumbnail for an image file. ⚠ Requires Dropbox-API-Arg header.',
    params: [
      { key: 'resource.path', type: 'body', required: true, hint: 'e.g. /Photos/photo.jpg', description: 'Path to the image file.' },
      { key: 'format',        type: 'body', required: false, hint: 'e.g. jpeg', description: 'jpeg or png.' },
      { key: 'size',          type: 'body', required: false, hint: 'e.g. w64h64', description: 'w32h32, w64h64, w128h128, w256h256, w480h320, w640h480, w960h640, w1024h768, w2048h1536.' },
    ],
  },

  // ── SHARING ────────────────────────────────────────────────────────────────
  {
    id: 'sharing-list-shared-links',
    group: 'Sharing',
    name: 'List Shared Links',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/list_shared_links',
    description: 'Lists all shared links for a file or folder, or all shared links the user has created.',
    params: [
      { key: 'path',            type: 'body', required: false, hint: 'e.g. /Documents/report.pdf', description: 'Path to list links for. Omit to get all your links.' },
      { key: 'cursor',          type: 'body', required: false, hint: 'e.g. <cursor from previous response>', description: 'For pagination.' },
      { key: 'direct_only',     type: 'body', required: false, hint: 'e.g. false', description: 'If true, returns only direct links to the item.' },
    ],
  },
  {
    id: 'sharing-create-shared-link',
    group: 'Sharing',
    name: 'Create Shared Link',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/create_shared_link_with_settings',
    description: 'Creates a shared link with custom settings (password, expiry, permissions).',
    params: [
      { key: 'path',                     type: 'body', required: true,  hint: 'e.g. /Documents/report.pdf', description: 'Dropbox path to share.' },
      { key: 'settings.requested_visibility', type: 'body', required: false, hint: 'e.g. public', description: 'public, team_only, or password.' },
      { key: 'settings.link_password',   type: 'body', required: false, hint: 'e.g. mypassword', description: 'Password to protect the link.' },
      { key: 'settings.expires',         type: 'body', required: false, hint: 'e.g. 2025-12-31T00:00:00Z', description: 'Link expiry (ISO 8601 UTC).' },
    ],
  },
  {
    id: 'sharing-get-shared-link-metadata',
    group: 'Sharing',
    name: 'Get Shared Link Metadata',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/get_shared_link_metadata',
    description: 'Returns metadata about a shared link (file or folder info, permissions, expiry).',
    params: [
      { key: 'url',  type: 'body', required: true,  hint: 'e.g. https://www.dropbox.com/s/abc123/file.pdf', description: 'The shared link URL.' },
      { key: 'path', type: 'body', required: false, hint: 'e.g. /subfolder/file.pdf', description: 'Path inside the shared folder (for folder links).' },
    ],
  },
  {
    id: 'sharing-modify-shared-link-settings',
    group: 'Sharing',
    name: 'Modify Shared Link Settings',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/modify_shared_link_settings',
    description: 'Modifies the settings of an existing shared link.',
    params: [
      { key: 'url',                      type: 'body', required: true,  hint: 'e.g. https://www.dropbox.com/s/abc123/file.pdf', description: 'The shared link URL to modify.' },
      { key: 'settings.requested_visibility', type: 'body', required: false, hint: 'e.g. team_only', description: 'New visibility: public, team_only, or password.' },
      { key: 'settings.link_password',   type: 'body', required: false, hint: 'e.g. newpassword', description: 'New link password.' },
      { key: 'settings.expires',         type: 'body', required: false, hint: 'e.g. 2025-12-31T00:00:00Z', description: 'New expiry date.' },
      { key: 'remove_expiration',        type: 'body', required: false, hint: 'e.g. false', description: 'Set true to remove the expiration date.' },
    ],
  },
  {
    id: 'sharing-revoke-shared-link',
    group: 'Sharing',
    name: 'Revoke Shared Link',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/revoke_shared_link',
    description: 'Revokes (disables) a shared link.',
    params: [
      { key: 'url', type: 'body', required: true, hint: 'e.g. https://www.dropbox.com/s/abc123/file.pdf', description: 'The shared link URL to revoke.' },
    ],
  },
  {
    id: 'sharing-get-file-metadata',
    group: 'Sharing',
    name: 'Get Shared File Metadata',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/get_file_metadata',
    description: 'Returns sharing metadata for a file the user owns or has access to.',
    params: [
      { key: 'file',    type: 'body', required: true,  hint: 'e.g. id:abc123 or /path/file.pdf', description: 'Dropbox file ID or path.' },
      { key: 'actions', type: 'body', required: false, hint: 'e.g. ["edit_contents"]', description: 'List of sharing actions to check permissions for.' },
    ],
  },
  {
    id: 'sharing-list-folder-members',
    group: 'Sharing',
    name: 'List Shared Folder Members',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/list_folder_members',
    description: 'Returns all members (users, groups, invitees) of a shared folder.',
    params: [
      { key: 'shared_folder_id', type: 'body', required: true, hint: 'e.g. 84528192421', description: 'The ID of the shared folder.' },
      { key: 'limit',            type: 'body', required: false, hint: 'e.g. 100', description: 'Max members to return.' },
    ],
  },
  {
    id: 'sharing-list-folder-members-continue',
    group: 'Sharing',
    name: 'List Shared Folder Members — Continue',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/list_folder_members/continue',
    description: 'Continues listing shared folder members from a previous call.',
    params: [
      { key: 'cursor', type: 'body', required: true, hint: 'e.g. <cursor from list_folder_members>', description: 'Cursor from list_folder_members.' },
    ],
  },
  {
    id: 'sharing-list-folders',
    group: 'Sharing',
    name: 'List Shared Folders',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/list_folders',
    description: 'Returns all shared folders the current user has access to.',
    params: [
      { key: 'limit',   type: 'body', required: false, hint: 'e.g. 100', description: 'Max shared folders to return.' },
      { key: 'actions', type: 'body', required: false, hint: 'e.g. ["leave_a_copy"]', description: 'Actions to check permissions for.' },
    ],
  },
  {
    id: 'sharing-list-folders-continue',
    group: 'Sharing',
    name: 'List Shared Folders — Continue',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/list_folders/continue',
    description: 'Continues listing shared folders from a previous call.',
    params: [
      { key: 'cursor', type: 'body', required: true, hint: 'e.g. <cursor from list_folders>', description: 'Cursor from list_folders.' },
    ],
  },
  {
    id: 'sharing-list-received-files',
    group: 'Sharing',
    name: 'List Received Files',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/list_received_files',
    description: 'Returns files shared directly with the current user.',
    params: [
      { key: 'limit', type: 'body', required: false, hint: 'e.g. 100', description: 'Max files to return (max 300).' },
    ],
  },
  {
    id: 'sharing-get-folder-metadata',
    group: 'Sharing',
    name: 'Get Shared Folder Metadata',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/get_folder_metadata',
    description: 'Returns metadata about a shared folder.',
    params: [
      { key: 'shared_folder_id', type: 'body', required: true, hint: 'e.g. 84528192421', description: 'ID of the shared folder.' },
    ],
  },
  {
    id: 'sharing-add-folder-member',
    group: 'Sharing',
    name: 'Add Folder Member',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/add_folder_member',
    description: 'Adds a member to a shared folder.',
    params: [
      { key: 'shared_folder_id', type: 'body', required: true, hint: 'e.g. 84528192421', description: 'ID of the shared folder.' },
      { key: 'members',          type: 'body', required: true, hint: 'e.g. [{"member":{"tag":"email","email":"user@example.com"},"access_level":"viewer"}]', description: 'Array of member specs.' },
      { key: 'quiet',            type: 'body', required: false, hint: 'e.g. false', description: 'If true, skip notification email.' },
    ],
  },
  {
    id: 'sharing-remove-folder-member',
    group: 'Sharing',
    name: 'Remove Folder Member',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/remove_folder_member',
    description: 'Removes a member from a shared folder.',
    params: [
      { key: 'shared_folder_id', type: 'body', required: true, hint: 'e.g. 84528192421', description: 'ID of the shared folder.' },
      { key: 'member.tag',       type: 'body', required: true, hint: 'e.g. email', description: 'email or dropbox_id.' },
      { key: 'member.email',     type: 'body', required: false, hint: 'e.g. user@example.com', description: 'Email of the member to remove.' },
      { key: 'leave_a_copy',     type: 'body', required: true, hint: 'e.g. false', description: 'If true, the removed user keeps a copy.' },
    ],
  },
  {
    id: 'sharing-share-folder',
    group: 'Sharing',
    name: 'Share Folder',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/share_folder',
    description: 'Shares a folder with specified settings.',
    params: [
      { key: 'path',                   type: 'body', required: true,  hint: 'e.g. /Documents/Team', description: 'Dropbox path to share.' },
      { key: 'acl_update_policy',      type: 'body', required: false, hint: 'e.g. editors', description: 'Who can manage membership: owner or editors.' },
      { key: 'member_policy',          type: 'body', required: false, hint: 'e.g. team', description: 'Who can join: team or anyone.' },
      { key: 'shared_link_policy',     type: 'body', required: false, hint: 'e.g. team', description: 'Who can use shared links: anyone, team, or no_one.' },
    ],
  },
  {
    id: 'sharing-unshare-folder',
    group: 'Sharing',
    name: 'Unshare Folder',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/unshare_folder',
    description: 'Unshares a folder — removes all members except the owner.',
    params: [
      { key: 'shared_folder_id', type: 'body', required: true, hint: 'e.g. 84528192421', description: 'ID of the shared folder.' },
      { key: 'leave_a_copy',     type: 'body', required: false, hint: 'e.g. false', description: 'If true, members keep a copy.' },
    ],
  },
  {
    id: 'sharing-transfer-folder',
    group: 'Sharing',
    name: 'Transfer Folder Ownership',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/sharing/transfer_folder',
    description: 'Transfers ownership of a shared folder to another member.',
    params: [
      { key: 'shared_folder_id', type: 'body', required: true, hint: 'e.g. 84528192421', description: 'ID of the shared folder.' },
      { key: 'to_dropbox_id',    type: 'body', required: true, hint: 'e.g. dbid:AAH...',  description: 'Dropbox account ID of the new owner.' },
    ],
  },

  // ── USERS ─────────────────────────────────────────────────────────────────
  {
    id: 'users-get-current-account',
    group: 'Users',
    name: 'Get Current Account',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/users/get_current_account',
    description: 'Returns information about the currently authenticated account.',
    params: [],
  },
  {
    id: 'users-get-space-usage',
    group: 'Users',
    name: 'Get Space Usage',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/users/get_space_usage',
    description: 'Returns storage allocation and current usage for the current account.',
    params: [],
  },
  {
    id: 'users-get-account',
    group: 'Users',
    name: 'Get Account Info (by ID)',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/users/get_account',
    description: 'Returns public info about any Dropbox account given its account ID.',
    params: [
      { key: 'account_id', type: 'body', required: true, hint: 'e.g. dbid:AAH4f99T0taONIb-OurWxbNQ6ywGRopQkGA', description: 'The Dropbox account ID.' },
    ],
  },
  {
    id: 'users-get-account-batch',
    group: 'Users',
    name: 'Get Account Batch (multiple IDs)',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/users/get_account_batch',
    description: 'Returns public info for multiple Dropbox accounts in one call.',
    params: [
      { key: 'account_ids', type: 'body', required: true, hint: 'e.g. ["dbid:AAH4f99T0taONIb...", "dbid:..."]', description: 'Array of account IDs (max 300).' },
    ],
  },

  // ── FILE REQUESTS ─────────────────────────────────────────────────────────
  {
    id: 'file-requests-count',
    group: 'File Requests',
    name: 'Count File Requests',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/file_requests/count',
    description: 'Returns the total number of file requests for the current user.',
    params: [],
  },
  {
    id: 'file-requests-list-v2',
    group: 'File Requests',
    name: 'List File Requests',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/file_requests/list_v2',
    description: 'Lists all file requests created by the current user.',
    params: [
      { key: 'limit', type: 'body', required: false, hint: 'e.g. 1000', description: 'Max file requests to return (max 1000).' },
    ],
  },
  {
    id: 'file-requests-list-continue',
    group: 'File Requests',
    name: 'List File Requests — Continue',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/file_requests/list/continue',
    description: 'Continues listing file requests from a previous call.',
    params: [
      { key: 'cursor', type: 'body', required: true, hint: 'e.g. <cursor from list_v2>', description: 'Cursor from list_v2.' },
    ],
  },
  {
    id: 'file-requests-get',
    group: 'File Requests',
    name: 'Get File Request',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/file_requests/get',
    description: 'Returns info about a specific file request.',
    params: [
      { key: 'id', type: 'body', required: true, hint: 'e.g. 1234abc', description: 'The ID of the file request.' },
    ],
  },
  {
    id: 'file-requests-create',
    group: 'File Requests',
    name: 'Create File Request',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/file_requests/create',
    description: 'Creates a new file request — generates a link where others can upload files to your Dropbox.',
    params: [
      { key: 'title',        type: 'body', required: true,  hint: 'e.g. Q4 Reports', description: 'The title of the file request.' },
      { key: 'destination',  type: 'body', required: true,  hint: 'e.g. /Shared/uploads', description: 'Dropbox folder where uploads will go.' },
      { key: 'open',         type: 'body', required: false, hint: 'e.g. true', description: 'Whether the request is open for submissions.' },
      { key: 'deadline.deadline', type: 'body', required: false, hint: 'e.g. 2025-12-31T00:00:00Z', description: 'Deadline for submissions (ISO 8601).' },
    ],
  },
  {
    id: 'file-requests-update',
    group: 'File Requests',
    name: 'Update File Request',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/file_requests/update',
    description: 'Updates an existing file request.',
    params: [
      { key: 'id',           type: 'body', required: true,  hint: 'e.g. 1234abc', description: 'The file request ID to update.' },
      { key: 'title',        type: 'body', required: false, hint: 'e.g. Updated Title', description: 'New title.' },
      { key: 'destination',  type: 'body', required: false, hint: 'e.g. /New/Path', description: 'New destination folder.' },
      { key: 'open',         type: 'body', required: false, hint: 'e.g. false', description: 'Open or close the request.' },
    ],
  },
  {
    id: 'file-requests-delete',
    group: 'File Requests',
    name: 'Delete File Requests',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/file_requests/delete',
    description: 'Deletes one or more closed file requests.',
    params: [
      { key: 'ids', type: 'body', required: true, hint: 'e.g. ["1234abc", "5678def"]', description: 'Array of file request IDs to delete.' },
    ],
  },

  // ── AUTH ──────────────────────────────────────────────────────────────────
  {
    id: 'auth-token-revoke',
    group: 'Auth',
    name: 'Revoke Token',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/auth/token/revoke',
    description: 'Revokes the current access token — logs out the authenticated user.',
    params: [],
  },

  // ── CHECK ─────────────────────────────────────────────────────────────────
  {
    id: 'check-user',
    group: 'Check',
    name: 'Check User Connection',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/check/user',
    description: 'Tests that the user token is valid and the API is reachable.',
    params: [
      { key: 'query', type: 'body', required: false, hint: 'e.g. ping', description: 'Any string — echoed back in the response.' },
    ],
  },
  {
    id: 'check-app',
    group: 'Check',
    name: 'Check App Connection',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/check/app',
    description: 'Tests app-level (client_credentials) connectivity.',
    params: [
      { key: 'query', type: 'body', required: false, hint: 'e.g. ping', description: 'Any string — echoed back.' },
    ],
  },

  // ── PAPER ─────────────────────────────────────────────────────────────────
  {
    id: 'paper-docs-list',
    group: 'Paper',
    name: 'List Paper Docs',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/paper/docs/list',
    description: 'Returns a list of all Paper docs the current user has access to.',
    params: [
      { key: 'filter_by',  type: 'body', required: false, hint: 'e.g. docs_accessed', description: 'docs_created or docs_accessed.' },
      { key: 'sort_by',    type: 'body', required: false, hint: 'e.g. modified', description: 'accessed, modified, or created.' },
      { key: 'sort_order', type: 'body', required: false, hint: 'e.g. descending', description: 'ascending or descending.' },
      { key: 'limit',      type: 'body', required: false, hint: 'e.g. 100', description: 'Max docs per page (1–1000).' },
    ],
  },
  {
    id: 'paper-docs-list-continue',
    group: 'Paper',
    name: 'List Paper Docs — Continue',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/paper/docs/list/continue',
    description: 'Continues listing Paper docs from a previous call.',
    params: [
      { key: 'cursor', type: 'body', required: true, hint: 'e.g. <cursor from docs/list>', description: 'Cursor from paper/docs/list.' },
    ],
  },
  {
    id: 'paper-docs-get-folder-info',
    group: 'Paper',
    name: 'Get Paper Doc Folder Info',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/paper/docs/get_folder_info',
    description: 'Returns the folder hierarchy for a Paper doc.',
    params: [
      { key: 'doc_id', type: 'body', required: true, hint: 'e.g. uaSmbXcCH1a2fkO', description: 'Paper doc ID.' },
    ],
  },
  {
    id: 'paper-docs-users-list',
    group: 'Paper',
    name: 'List Paper Doc Users',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/paper/docs/users/list',
    description: 'Lists all users who have access to a Paper doc.',
    params: [
      { key: 'doc_id',              type: 'body', required: true,  hint: 'e.g. uaSmbXcCH1a2fkO', description: 'Paper doc ID.' },
      { key: 'limit',               type: 'body', required: false, hint: 'e.g. 100', description: 'Max users to return (1–1000).' },
      { key: 'filter_by_permission',type: 'body', required: false, hint: 'e.g. view_and_comment', description: 'edit or view_and_comment.' },
    ],
  },
  {
    id: 'paper-docs-sharing-policy-get',
    group: 'Paper',
    name: 'Get Paper Doc Sharing Policy',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/paper/docs/sharing_policy/get',
    description: 'Gets the sharing policy of a Paper doc.',
    params: [
      { key: 'doc_id', type: 'body', required: true, hint: 'e.g. uaSmbXcCH1a2fkO', description: 'Paper doc ID.' },
    ],
  },
  {
    id: 'paper-docs-download',
    group: 'Paper',
    name: 'Download Paper Doc',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/paper/docs/download',
    description: 'Downloads a Paper doc in a specified format. ⚠ Requires Dropbox-API-Arg header.',
    params: [
      { key: 'doc_id',       type: 'body', required: true, hint: 'e.g. uaSmbXcCH1a2fkO', description: 'Paper doc ID.' },
      { key: 'export_format',type: 'body', required: true, hint: 'e.g. markdown', description: 'html or markdown.' },
    ],
  },
  {
    id: 'paper-docs-create',
    group: 'Paper',
    name: 'Create Paper Doc',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/paper/docs/create',
    description: 'Creates a new Paper doc with optional initial content.',
    params: [
      { key: 'import_format',     type: 'body', required: true,  hint: 'e.g. markdown', description: 'html, plain_text, or markdown.' },
      { key: 'parent_folder_id',  type: 'body', required: false, hint: 'e.g. e.UACTanlTddhV2rHdaL', description: 'Folder to create the doc in (optional).' },
    ],
  },
  {
    id: 'paper-docs-archive',
    group: 'Paper',
    name: 'Archive Paper Doc',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/paper/docs/archive',
    description: 'Archives a Paper doc. Only the owner can archive.',
    params: [
      { key: 'doc_id', type: 'body', required: true, hint: 'e.g. uaSmbXcCH1a2fkO', description: 'Paper doc ID.' },
    ],
  },
  {
    id: 'paper-docs-permanently-delete',
    group: 'Paper',
    name: 'Permanently Delete Paper Doc',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/paper/docs/permanently_delete',
    description: 'Permanently deletes a Paper doc. Must be archived first.',
    params: [
      { key: 'doc_id', type: 'body', required: true, hint: 'e.g. uaSmbXcCH1a2fkO', description: 'Paper doc ID.' },
    ],
  },
  {
    id: 'paper-folders-list',
    group: 'Paper',
    name: 'List Paper Folders',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/paper/folders/list',
    description: 'Lists all Paper folders visible to the current user.',
    params: [
      { key: 'filter_by',  type: 'body', required: false, hint: 'e.g. team_folders', description: 'team_folders or personal_folders.' },
      { key: 'limit',      type: 'body', required: false, hint: 'e.g. 100', description: 'Max folders to return.' },
    ],
  },

  // ── FILE PROPERTIES ───────────────────────────────────────────────────────
  {
    id: 'file-properties-search',
    group: 'File Properties',
    name: 'Search by Properties',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/file_properties/properties/search',
    description: 'Searches for files/folders using custom property filters.',
    params: [
      { key: 'queries',         type: 'body', required: true, hint: 'e.g. [{"query":"2020","mode":{"tag":"field_query","field_key":"year"},"logical_operator":"or_operator"}]', description: 'Array of property search queries.' },
      { key: 'template_filter', type: 'body', required: false, hint: 'e.g. {"tag":"filter_none"}', description: 'Template filter.' },
    ],
  },
  {
    id: 'file-properties-templates-get-for-user',
    group: 'File Properties',
    name: 'Get Property Template (User)',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/file_properties/templates/get_for_user',
    description: 'Returns the schema of a specific user-level property template.',
    params: [
      { key: 'template_id', type: 'body', required: true, hint: 'e.g. ptid:1a5n2i6d3OYEAAAAAAAAAYa', description: 'The property template ID.' },
    ],
  },
  {
    id: 'file-properties-templates-list-for-user',
    group: 'File Properties',
    name: 'List Property Templates (User)',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/file_properties/templates/list_for_user',
    description: 'Lists all user-level custom property templates.',
    params: [],
  },

  // ── TEAM (Business API) ───────────────────────────────────────────────────
  {
    id: 'team-get-info',
    group: 'Team',
    name: 'Get Team Info',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/get_info',
    description: 'Returns information about the current team (name, license count, policies). Requires team admin token.',
    params: [],
  },
  {
    id: 'team-features-get-values',
    group: 'Team',
    name: 'Get Team Feature Values',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/features/get_values',
    description: 'Returns the values of team features enabled for the account.',
    params: [
      { key: 'features', type: 'body', required: true, hint: 'e.g. [{"tag":"upload_api_rate_limit"},{"tag":"has_team_shared_dropbox"}]', description: 'List of feature tags to query.' },
    ],
  },
  {
    id: 'team-members-list-v2',
    group: 'Team',
    name: 'List Team Members',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/members/list_v2',
    description: 'Returns a list of all members of the Dropbox Business team.',
    params: [
      { key: 'limit',         type: 'body', required: false, hint: 'e.g. 1000', description: 'Max members per call (max 1000).' },
      { key: 'include_removed', type: 'body', required: false, hint: 'e.g. false', description: 'If true, include removed members.' },
    ],
  },
  {
    id: 'team-members-list-continue-v2',
    group: 'Team',
    name: 'List Team Members — Continue',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/members/list/continue_v2',
    description: 'Continues listing team members from a previous call.',
    params: [
      { key: 'cursor', type: 'body', required: true, hint: 'e.g. <cursor from members/list_v2>', description: 'Cursor from members/list_v2.' },
    ],
  },
  {
    id: 'team-members-get-info',
    group: 'Team',
    name: 'Get Team Member Info',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/members/get_info',
    description: 'Returns info (profile, roles, status) for specified team members.',
    params: [
      { key: 'members', type: 'body', required: true, hint: 'e.g. [{"tag":"team_member_id","team_member_id":"dbmid:abc123"}]', description: 'Array of member selectors.' },
    ],
  },
  {
    id: 'team-members-set-profile',
    group: 'Team',
    name: 'Set Member Profile',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/members/set_profile',
    description: 'Updates a team member profile (name, email, persistent ID).',
    params: [
      { key: 'user.tag',            type: 'body', required: true,  hint: 'e.g. team_member_id', description: 'team_member_id or email.' },
      { key: 'user.team_member_id', type: 'body', required: false, hint: 'e.g. dbmid:abc123', description: 'Team member ID.' },
      { key: 'new_email',           type: 'body', required: false, hint: 'e.g. newemail@example.com', description: 'New email address.' },
      { key: 'new_given_name',      type: 'body', required: false, hint: 'e.g. John', description: 'New first name.' },
      { key: 'new_surname',         type: 'body', required: false, hint: 'e.g. Doe', description: 'New last name.' },
    ],
  },
  {
    id: 'team-members-suspend',
    group: 'Team',
    name: 'Suspend Team Member',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/members/suspend',
    description: 'Suspends a team member — prevents login while preserving data.',
    params: [
      { key: 'user.tag',            type: 'body', required: true, hint: 'e.g. team_member_id', description: 'team_member_id or email.' },
      { key: 'user.team_member_id', type: 'body', required: false, hint: 'e.g. dbmid:abc123', description: 'Team member ID.' },
      { key: 'wipe_data',           type: 'body', required: false, hint: 'e.g. false', description: 'If true, wipe data from linked devices.' },
    ],
  },
  {
    id: 'team-members-unsuspend',
    group: 'Team',
    name: 'Unsuspend Team Member',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/members/unsuspend',
    description: 'Reactivates a previously suspended team member.',
    params: [
      { key: 'user.tag',            type: 'body', required: true, hint: 'e.g. team_member_id', description: 'team_member_id or email.' },
      { key: 'user.team_member_id', type: 'body', required: false, hint: 'e.g. dbmid:abc123', description: 'Team member ID.' },
    ],
  },
  {
    id: 'team-members-remove',
    group: 'Team',
    name: 'Remove Team Member',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/members/remove',
    description: 'Removes a member from the team. Their account is deactivated.',
    params: [
      { key: 'user.tag',            type: 'body', required: true, hint: 'e.g. team_member_id', description: 'team_member_id or email.' },
      { key: 'user.team_member_id', type: 'body', required: false, hint: 'e.g. dbmid:abc123', description: 'Team member ID.' },
      { key: 'wipe_data',           type: 'body', required: false, hint: 'e.g. false', description: 'Wipe Dropbox data from devices.' },
      { key: 'keep_account',        type: 'body', required: false, hint: 'e.g. false', description: 'Convert to personal account instead of deleting.' },
    ],
  },
  {
    id: 'team-members-set-admin-permissions',
    group: 'Team',
    name: 'Set Admin Permissions',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/members/set_admin_permissions',
    description: 'Sets or removes admin roles for a team member.',
    params: [
      { key: 'user.tag',            type: 'body', required: true, hint: 'e.g. team_member_id', description: 'Member selector.' },
      { key: 'user.team_member_id', type: 'body', required: false, hint: 'e.g. dbmid:abc123', description: 'Team member ID.' },
      { key: 'new_role',            type: 'body', required: true, hint: 'e.g. member_only', description: 'member_only, support_admin, user_management_admin, team_admin.' },
    ],
  },
  {
    id: 'team-groups-list',
    group: 'Team',
    name: 'List Team Groups',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/groups/list',
    description: 'Lists all groups in the team.',
    params: [
      { key: 'limit', type: 'body', required: false, hint: 'e.g. 1000', description: 'Max groups per call (max 1000).' },
    ],
  },
  {
    id: 'team-groups-list-continue',
    group: 'Team',
    name: 'List Team Groups — Continue',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/groups/list/continue',
    description: 'Continues listing team groups from a previous call.',
    params: [
      { key: 'cursor', type: 'body', required: true, hint: 'e.g. <cursor from groups/list>', description: 'Cursor from groups/list.' },
    ],
  },
  {
    id: 'team-groups-get-info',
    group: 'Team',
    name: 'Get Group Info',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/groups/get_info',
    description: 'Returns detailed info (members count, type) for specified groups.',
    params: [
      { key: 'groups', type: 'body', required: true, hint: 'e.g. [{"tag":"group_id","group_id":"g:e2db7665347abcd600000000001a2b3c"}]', description: 'Array of group selectors.' },
    ],
  },
  {
    id: 'team-groups-members-list',
    group: 'Team',
    name: 'List Group Members',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/groups/members/list',
    description: 'Returns all members of a specific team group.',
    params: [
      { key: 'group.tag',      type: 'body', required: true, hint: 'e.g. group_id', description: 'group_id or group_external_id.' },
      { key: 'group.group_id', type: 'body', required: false, hint: 'e.g. g:e2db7665347abcd600000000001a2b3c', description: 'The Dropbox group ID.' },
      { key: 'limit',          type: 'body', required: false, hint: 'e.g. 1000', description: 'Max members to return.' },
    ],
  },
  {
    id: 'team-groups-create',
    group: 'Team',
    name: 'Create Group',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/groups/create',
    description: 'Creates a new team group.',
    params: [
      { key: 'group_name',        type: 'body', required: true,  hint: 'e.g. Engineering', description: 'Name for the new group.' },
      { key: 'group_external_id', type: 'body', required: false, hint: 'e.g. engineering-001', description: 'External ID for syncing with your directory.' },
      { key: 'group_management_type', type: 'body', required: false, hint: 'e.g. user_managed', description: 'user_managed or company_managed.' },
    ],
  },
  {
    id: 'team-groups-delete',
    group: 'Team',
    name: 'Delete Group',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/groups/delete',
    description: 'Deletes a team group.',
    params: [
      { key: 'group.tag',      type: 'body', required: true, hint: 'e.g. group_id', description: 'group_id or group_external_id.' },
      { key: 'group.group_id', type: 'body', required: false, hint: 'e.g. g:e2db7665347abcd600000000001a2b3c', description: 'The Dropbox group ID.' },
    ],
  },
  {
    id: 'team-devices-list-members-devices',
    group: 'Team',
    name: 'List Members\' Devices',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/devices/list_members_devices',
    description: 'Lists all devices linked by team members.',
    params: [
      { key: 'cursor',                   type: 'body', required: false, hint: 'e.g. <cursor from previous response>', description: 'For pagination.' },
      { key: 'include_web_sessions',     type: 'body', required: false, hint: 'e.g. true', description: 'Include web browser sessions.' },
      { key: 'include_desktop_clients',  type: 'body', required: false, hint: 'e.g. true', description: 'Include desktop clients.' },
      { key: 'include_mobile_clients',   type: 'body', required: false, hint: 'e.g. true', description: 'Include mobile apps.' },
    ],
  },
  {
    id: 'team-linked-apps-list-team-apps',
    group: 'Team',
    name: 'List Team Linked Apps',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/linked_apps/list_team_apps',
    description: 'Lists all third-party apps linked by team members.',
    params: [
      { key: 'cursor', type: 'body', required: false, hint: 'e.g. <cursor from previous response>', description: 'For pagination.' },
    ],
  },
  {
    id: 'team-namespaces-list',
    group: 'Team',
    name: 'List Team Namespaces',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/namespaces/list',
    description: 'Lists all namespaces (shared folders, team folders, member folders) in the team.',
    params: [
      { key: 'limit', type: 'body', required: false, hint: 'e.g. 1000', description: 'Max namespaces per call (max 1000).' },
    ],
  },
  {
    id: 'team-member-space-limits-get-custom-quota',
    group: 'Team',
    name: 'Get Members\' Custom Storage Quota',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/member_space_limits/get_custom_quota',
    description: 'Returns the custom storage quota for specified team members.',
    params: [
      { key: 'users', type: 'body', required: true, hint: 'e.g. [{"tag":"team_member_id","team_member_id":"dbmid:abc"}]', description: 'Array of user selectors.' },
    ],
  },
  {
    id: 'team-member-space-limits-set-custom-quota',
    group: 'Team',
    name: 'Set Members\' Custom Storage Quota',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/member_space_limits/set_custom_quota',
    description: 'Sets a custom storage quota for specified team members.',
    params: [
      { key: 'users_and_quotas', type: 'body', required: true, hint: 'e.g. [{"user":{"tag":"team_member_id","team_member_id":"dbmid:abc"},"quota_gb":100}]', description: 'Array of user+quota pairs.' },
    ],
  },
  {
    id: 'team-sharing-list-shared-links',
    group: 'Team',
    name: 'List All Team Shared Links (Admin)',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/sharing/list_shared_links',
    description: 'Lists all shared links created by any team member. Requires team admin token.',
    params: [
      { key: 'has_sp_shared_folder',type: 'body', required: false, hint: 'e.g. false', description: 'Filter to shared folder links.' },
      { key: 'cursor',              type: 'body', required: false, hint: 'e.g. <cursor from previous response>', description: 'For pagination.' },
    ],
  },

  // ── TEAM LOG ──────────────────────────────────────────────────────────────
  {
    id: 'team-log-get-events',
    group: 'Team Log',
    name: 'Get Audit Log Events',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team_log/get_events',
    description: 'Returns audit log events for the team. Useful for compliance and security reviews.',
    params: [
      { key: 'limit',      type: 'body', required: false, hint: 'e.g. 1000', description: 'Max events per call (max 1000).' },
      { key: 'account_id', type: 'body', required: false, hint: 'e.g. dbid:AAH4f99T0...', description: 'Filter to events for a specific member.' },
      { key: 'time.start_time', type: 'body', required: false, hint: 'e.g. 2024-01-01T00:00:00Z', description: 'Start of time range (ISO 8601).' },
      { key: 'time.end_time',   type: 'body', required: false, hint: 'e.g. 2024-12-31T23:59:59Z', description: 'End of time range (ISO 8601).' },
      { key: 'event_type.tag',  type: 'body', required: false, hint: 'e.g. file_operations', description: 'Event category filter.' },
    ],
  },
  {
    id: 'team-log-get-events-continue',
    group: 'Team Log',
    name: 'Get Audit Log Events — Continue',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team_log/get_events/continue',
    description: 'Continues fetching audit log events from a previous call.',
    params: [
      { key: 'cursor', type: 'body', required: true, hint: 'e.g. <cursor from get_events>', description: 'Cursor from get_events.' },
    ],
  },

  // ── TEAM REPORTS ──────────────────────────────────────────────────────────
  {
    id: 'team-reports-get-membership',
    group: 'Team Reports',
    name: 'Report — Membership',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/reports/get_membership',
    description: 'Returns a report on team membership changes over a date range.',
    params: [
      { key: 'start_date', type: 'body', required: false, hint: 'e.g. 2024-01-01', description: 'Start date (YYYY-MM-DD). Defaults to 1 week ago.' },
      { key: 'end_date',   type: 'body', required: false, hint: 'e.g. 2024-01-31', description: 'End date (YYYY-MM-DD).' },
    ],
  },
  {
    id: 'team-reports-get-storage',
    group: 'Team Reports',
    name: 'Report — Storage',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/reports/get_storage',
    description: 'Returns a report on team storage usage over a date range.',
    params: [
      { key: 'start_date', type: 'body', required: false, hint: 'e.g. 2024-01-01', description: 'Start date (YYYY-MM-DD).' },
      { key: 'end_date',   type: 'body', required: false, hint: 'e.g. 2024-01-31', description: 'End date (YYYY-MM-DD).' },
    ],
  },
  {
    id: 'team-reports-get-activity',
    group: 'Team Reports',
    name: 'Report — Activity',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/reports/get_activity',
    description: 'Returns a report on team member activity over a date range.',
    params: [
      { key: 'start_date', type: 'body', required: false, hint: 'e.g. 2024-01-01', description: 'Start date (YYYY-MM-DD).' },
      { key: 'end_date',   type: 'body', required: false, hint: 'e.g. 2024-01-31', description: 'End date (YYYY-MM-DD).' },
    ],
  },
  {
    id: 'team-reports-get-devices',
    group: 'Team Reports',
    name: 'Report — Devices',
    method: 'POST',
    baseUrl: 'https://api.dropboxapi.com/2/team/reports/get_devices',
    description: 'Returns a report on linked devices across the team.',
    params: [
      { key: 'start_date', type: 'body', required: false, hint: 'e.g. 2024-01-01', description: 'Start date (YYYY-MM-DD).' },
      { key: 'end_date',   type: 'body', required: false, hint: 'e.g. 2024-01-31', description: 'End date (YYYY-MM-DD).' },
    ],
  },
];
