// Egnyte Public API — https://developers.egnyte.com/
// Two API versions:
//   File System & Links: https://{domain}.egnyte.com/pubapi/v1/
//   Users & Groups:      https://{domain}.egnyte.com/pubapi/v2/

export const egnyteAPIs = [

  // ── FILE SYSTEM — Read ────────────────────────────────────────────────────
  {
    id: 'fs-get-folder',
    group: 'File System — Read',
    name: 'List Folder Contents',
    method: 'GET',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/fs/{folderPath}',
    description: 'Lists the files and sub-folders inside an Egnyte folder. Use an empty path to list the root.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain (before .egnyte.com).' },
      { key: 'folderPath',   type: 'path', required: true, hint: "e.g. Shared/Clients  (or leave empty for root)", description: 'Path to the folder in Egnyte (no leading slash).' },
    ],
  },
  {
    id: 'fs-get-file',
    group: 'File System — Read',
    name: 'Get File / Folder Metadata',
    method: 'GET',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/fs/{path}',
    description: 'Returns metadata (size, modified date, checksum, path) for a specific file or folder.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'path',         type: 'path', required: true, hint: "e.g. Shared/Clients/Moody's Analytics/report.pdf", description: 'Full Egnyte path to the file or folder.' },
    ],
  },
  {
    id: 'fs-download-file',
    group: 'File System — Read',
    name: 'Download File',
    method: 'GET',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/fs-content/{filePath}',
    description: 'Downloads the content of a file.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'filePath',     type: 'path', required: true, hint: 'e.g. Shared/Documents/report.pdf', description: 'Full Egnyte path to the file.' },
    ],
  },
  {
    id: 'fs-list-file-versions',
    group: 'File System — Read',
    name: 'List File Versions',
    method: 'GET',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/fs/{filePath}?list_versions=1',
    description: 'Returns all past versions of a file.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'filePath',     type: 'path', required: true, hint: 'e.g. Shared/Documents/report.pdf', description: 'Full Egnyte path to the file.' },
    ],
  },
  {
    id: 'fs-get-file-lock',
    group: 'File System — Read',
    name: 'Check File Lock Status',
    method: 'GET',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/fs/{filePath}?lock=1',
    description: 'Returns the lock status of a file.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'filePath',     type: 'path', required: true, hint: 'e.g. Shared/Documents/report.docx', description: 'Full Egnyte file path.' },
    ],
  },

  // ── FILE SYSTEM — Write ───────────────────────────────────────────────────
  {
    id: 'fs-create-folder',
    group: 'File System — Write',
    name: 'Create Folder',
    method: 'POST',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/fs/{folderPath}',
    description: 'Creates a new folder at the given path.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'folderPath',   type: 'path', required: true, hint: 'e.g. Shared/NewFolder', description: 'Full path for the new folder.' },
      { key: 'action',       type: 'body', required: true, hint: 'e.g. add_folder', description: 'Must be add_folder.' },
    ],
  },
  {
    id: 'fs-upload-file',
    group: 'File System — Write',
    name: 'Upload File',
    method: 'POST',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/fs-content/{filePath}',
    description: 'Uploads a file. ⚠ Requires multipart form data or raw file content in the body.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'filePath',     type: 'path', required: true, hint: 'e.g. Shared/Documents/upload.pdf', description: 'Full Egnyte path to save the file at.' },
    ],
  },
  {
    id: 'fs-move-file',
    group: 'File System — Write',
    name: 'Move File / Folder',
    method: 'POST',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/fs/{sourcePath}',
    description: 'Moves a file or folder to a new location.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'sourcePath',   type: 'path', required: true, hint: 'e.g. Shared/OldLocation/file.pdf', description: 'Current path of the file or folder.' },
      { key: 'action',       type: 'body', required: true, hint: 'e.g. move', description: 'Must be move.' },
      { key: 'destination',  type: 'body', required: true, hint: 'e.g. /Shared/NewLocation/file.pdf', description: 'Destination path (with leading slash).' },
    ],
  },
  {
    id: 'fs-copy-file',
    group: 'File System — Write',
    name: 'Copy File / Folder',
    method: 'POST',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/fs/{sourcePath}',
    description: 'Copies a file or folder to a new location.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'sourcePath',   type: 'path', required: true, hint: 'e.g. Shared/Documents/file.pdf', description: 'Source path.' },
      { key: 'action',       type: 'body', required: true, hint: 'e.g. copy', description: 'Must be copy.' },
      { key: 'destination',  type: 'body', required: true, hint: 'e.g. /Shared/Archive/file.pdf', description: 'Destination path (with leading slash).' },
    ],
  },
  {
    id: 'fs-delete',
    group: 'File System — Write',
    name: 'Delete File / Folder',
    method: 'DELETE',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/fs/{path}',
    description: 'Deletes a file or folder permanently.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'path',         type: 'path', required: true, hint: 'e.g. Shared/Documents/old-file.pdf', description: 'Path to delete.' },
    ],
  },
  {
    id: 'fs-lock-file',
    group: 'File System — Write',
    name: 'Lock File',
    method: 'POST',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/fs/{filePath}',
    description: 'Locks a file to prevent other users from editing it.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'filePath',     type: 'path', required: true, hint: 'e.g. Shared/Documents/report.docx', description: 'File to lock.' },
      { key: 'action',       type: 'body', required: true, hint: 'e.g. lock', description: 'Must be lock.' },
    ],
  },
  {
    id: 'fs-unlock-file',
    group: 'File System — Write',
    name: 'Unlock File',
    method: 'POST',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/fs/{filePath}',
    description: 'Unlocks a previously locked file.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'filePath',     type: 'path', required: true, hint: 'e.g. Shared/Documents/report.docx', description: 'File to unlock.' },
      { key: 'action',       type: 'body', required: true, hint: 'e.g. unlock', description: 'Must be unlock.' },
    ],
  },

  // ── SEARCH ────────────────────────────────────────────────────────────────
  {
    id: 'search-files',
    group: 'Search',
    name: 'Search Files / Folders',
    method: 'GET',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/search',
    description: 'Searches for files and folders matching a query string.',
    params: [
      { key: 'egnyteDomain', type: 'path',  required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'query',         type: 'query', required: true, hint: 'e.g. invoice 2024', description: 'Search query string.' },
      { key: 'type',          type: 'query', required: false, hint: 'e.g. file', description: 'Filter by type: file or folder.' },
      { key: 'folder',        type: 'query', required: false, hint: 'e.g. /Shared/Clients', description: 'Restrict search to this folder path.' },
      { key: 'startIndex',    type: 'query', required: false, hint: 'e.g. 0', description: 'Pagination start index.' },
      { key: 'count',         type: 'query', required: false, hint: 'e.g. 25', description: 'Max results to return.' },
    ],
  },

  // ── PERMISSIONS ───────────────────────────────────────────────────────────
  {
    id: 'permissions-get-folder',
    group: 'Permissions',
    name: 'Get Folder Permissions',
    method: 'GET',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/perms/folder/{folderPath}',
    description: 'Returns all permissions set on an Egnyte folder.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'folderPath',   type: 'path', required: true, hint: 'e.g. Shared/Clients', description: 'Folder path to get permissions for.' },
    ],
  },
  {
    id: 'permissions-set-folder',
    group: 'Permissions',
    name: 'Set Folder Permissions',
    method: 'POST',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/perms/folder/{folderPath}',
    description: 'Sets (overwrites) permissions on an Egnyte folder.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'folderPath',   type: 'path', required: true, hint: 'e.g. Shared/Clients', description: 'Folder path to set permissions on.' },
      { key: 'users',        type: 'body', required: false, hint: 'e.g. {"john.doe": "Viewer"}', description: 'User permission map: username → role.' },
      { key: 'groups',       type: 'body', required: false, hint: 'e.g. {"Engineering": "Editor"}', description: 'Group permission map: groupname → role.' },
    ],
  },
  {
    id: 'permissions-delete-folder',
    group: 'Permissions',
    name: 'Delete User/Group Folder Permission',
    method: 'DELETE',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/perms/folder/{folderPath}',
    description: 'Removes a specific user or group permission from a folder.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'folderPath',   type: 'path', required: true, hint: 'e.g. Shared/Clients', description: 'Folder path.' },
    ],
  },

  // ── LINKS ─────────────────────────────────────────────────────────────────
  {
    id: 'links-create',
    group: 'Links',
    name: 'Create Shared Link',
    method: 'POST',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/links',
    description: 'Creates a shared link to a file or folder.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'path',          type: 'body', required: true, hint: 'e.g. /Shared/Documents/report.pdf', description: 'Egnyte path to the file or folder.' },
      { key: 'type',          type: 'body', required: true, hint: 'e.g. file', description: 'Link type: file or folder.' },
      { key: 'accessibility', type: 'body', required: true, hint: 'e.g. anyone', description: 'anyone, password, domain, or recipients.' },
      { key: 'password',      type: 'body', required: false, hint: 'e.g. mypassword', description: 'Required when accessibility=password.' },
      { key: 'expiry_clicks', type: 'body', required: false, hint: 'e.g. 10', description: 'Max number of clicks before link expires.' },
      { key: 'expiry_date',   type: 'body', required: false, hint: 'e.g. 2025-12-31', description: 'Expiry date (YYYY-MM-DD).' },
      { key: 'link_to_current',type: 'body', required: false, hint: 'e.g. true', description: 'Link to the current version only.' },
    ],
  },
  {
    id: 'links-list',
    group: 'Links',
    name: 'List Shared Links',
    method: 'GET',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/links',
    description: 'Returns all shared links created by the current user.',
    params: [
      { key: 'egnyteDomain', type: 'path',  required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'path',          type: 'query', required: false, hint: 'e.g. /Shared/Documents', description: 'Filter links to this folder path.' },
      { key: 'username',      type: 'query', required: false, hint: 'e.g. john.doe', description: 'Filter links created by this user.' },
      { key: 'offset',        type: 'query', required: false, hint: 'e.g. 0', description: 'Pagination offset.' },
      { key: 'count',         type: 'query', required: false, hint: 'e.g. 25', description: 'Max links to return.' },
    ],
  },
  {
    id: 'links-get',
    group: 'Links',
    name: 'Get Shared Link',
    method: 'GET',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/links/{linkId}',
    description: 'Returns details for a specific shared link.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'linkId',       type: 'path', required: true, hint: 'e.g. HdaTz5p5YH8J', description: 'Link ID (from the shared link URL).' },
    ],
  },
  {
    id: 'links-delete',
    group: 'Links',
    name: 'Delete Shared Link',
    method: 'DELETE',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/links/{linkId}',
    description: 'Revokes (deletes) a shared link.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'linkId',       type: 'path', required: true, hint: 'e.g. HdaTz5p5YH8J', description: 'Link ID to revoke.' },
    ],
  },

  // ── USERS ─────────────────────────────────────────────────────────────────
  {
    id: 'users-list',
    group: 'Users',
    name: 'List Users',
    method: 'GET',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v2/users',
    description: 'Returns a paginated list of all users in the Egnyte domain.',
    params: [
      { key: 'egnyteDomain', type: 'path',  required: true, hint: 'e.g. democloudfuze', description: 'Your Egnyte subdomain.' },
      { key: 'count',         type: 'query', required: false, hint: 'e.g. 100', description: 'Number of users per page.' },
      { key: 'startIndex',    type: 'query', required: false, hint: 'e.g. 1', description: 'Starting index (1-based).' },
    ],
  },
  {
    id: 'users-get',
    group: 'Users',
    name: 'Get User',
    method: 'GET',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v2/users/{userId}',
    description: 'Returns details for a specific Egnyte user — status, role, storage used.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. democloudfuze', description: 'Your Egnyte subdomain.' },
      { key: 'userId',       type: 'path', required: true, hint: 'e.g. 12345', description: 'Egnyte user ID.' },
    ],
  },
  {
    id: 'users-create',
    group: 'Users',
    name: 'Create User',
    method: 'POST',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v2/users',
    description: 'Creates a new Egnyte user.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. democloudfuze', description: 'Your Egnyte subdomain.' },
      { key: 'userName',     type: 'body', required: true, hint: 'e.g. john.doe', description: 'Username (login).' },
      { key: 'email',        type: 'body', required: true, hint: 'e.g. john.doe@company.com', description: 'Email address.' },
      { key: 'name.formatted',type: 'body', required: false, hint: 'e.g. John Doe', description: 'Display name.' },
      { key: 'role',         type: 'body', required: false, hint: 'e.g. Viewer', description: 'Role: Administrator, Power User, Standard User, Viewer.' },
      { key: 'active',       type: 'body', required: false, hint: 'e.g. true', description: 'Whether the user account is active.' },
    ],
  },
  {
    id: 'users-update',
    group: 'Users',
    name: 'Update User',
    method: 'PATCH',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v2/users/{userId}',
    description: 'Updates a user\'s role, active status, or display name.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. democloudfuze', description: 'Your Egnyte subdomain.' },
      { key: 'userId',       type: 'path', required: true, hint: 'e.g. 12345', description: 'Egnyte user ID.' },
      { key: 'active',       type: 'body', required: false, hint: 'e.g. false', description: 'Disable/enable the account.' },
      { key: 'role',         type: 'body', required: false, hint: 'e.g. Standard User', description: 'New role.' },
    ],
  },
  {
    id: 'users-delete',
    group: 'Users',
    name: 'Delete User',
    method: 'DELETE',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v2/users/{userId}',
    description: 'Deletes a user from the Egnyte domain.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. democloudfuze', description: 'Your Egnyte subdomain.' },
      { key: 'userId',       type: 'path', required: true, hint: 'e.g. 12345', description: 'Egnyte user ID.' },
    ],
  },

  // ── GROUPS ────────────────────────────────────────────────────────────────
  {
    id: 'groups-list',
    group: 'Groups',
    name: 'List Groups',
    method: 'GET',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v2/groups',
    description: 'Returns all groups in the Egnyte domain.',
    params: [
      { key: 'egnyteDomain', type: 'path',  required: true, hint: 'e.g. democloudfuze', description: 'Your Egnyte subdomain.' },
      { key: 'count',         type: 'query', required: false, hint: 'e.g. 100', description: 'Max groups per page.' },
      { key: 'startIndex',    type: 'query', required: false, hint: 'e.g. 1', description: 'Starting index (1-based).' },
    ],
  },
  {
    id: 'groups-get',
    group: 'Groups',
    name: 'Get Group',
    method: 'GET',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v2/groups/{groupId}',
    description: 'Returns details for a specific Egnyte group — name, members.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. democloudfuze', description: 'Your Egnyte subdomain.' },
      { key: 'groupId',      type: 'path', required: true, hint: 'e.g. 99876', description: 'Egnyte group ID.' },
    ],
  },
  {
    id: 'groups-create',
    group: 'Groups',
    name: 'Create Group',
    method: 'POST',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v2/groups',
    description: 'Creates a new group in the Egnyte domain.',
    params: [
      { key: 'egnyteDomain',  type: 'path', required: true, hint: 'e.g. democloudfuze', description: 'Your Egnyte subdomain.' },
      { key: 'displayName',   type: 'body', required: true, hint: 'e.g. Engineering Team', description: 'Group display name.' },
      { key: 'members',       type: 'body', required: false, hint: 'e.g. [{"value": "12345"}]', description: 'Array of member objects with user IDs.' },
    ],
  },
  {
    id: 'groups-update',
    group: 'Groups',
    name: 'Update Group',
    method: 'PATCH',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v2/groups/{groupId}',
    description: 'Updates a group\'s name or members.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. democloudfuze', description: 'Your Egnyte subdomain.' },
      { key: 'groupId',      type: 'path', required: true, hint: 'e.g. 99876', description: 'Egnyte group ID.' },
      { key: 'displayName',  type: 'body', required: false, hint: 'e.g. Updated Name', description: 'New group name.' },
      { key: 'members',      type: 'body', required: false, hint: 'e.g. [{"value": "12345"}]', description: 'Updated member list.' },
    ],
  },
  {
    id: 'groups-delete',
    group: 'Groups',
    name: 'Delete Group',
    method: 'DELETE',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v2/groups/{groupId}',
    description: 'Deletes a group from the Egnyte domain.',
    params: [
      { key: 'egnyteDomain', type: 'path', required: true, hint: 'e.g. democloudfuze', description: 'Your Egnyte subdomain.' },
      { key: 'groupId',      type: 'path', required: true, hint: 'e.g. 99876', description: 'Egnyte group ID.' },
    ],
  },

  // ── AUDIT ─────────────────────────────────────────────────────────────────
  {
    id: 'audit-folder',
    group: 'Audit',
    name: 'Get Folder Audit Report',
    method: 'GET',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/audit/folder',
    description: 'Returns an audit trail of all actions on files/folders (upload, download, delete, move).',
    params: [
      { key: 'egnyteDomain', type: 'path',  required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'folder',        type: 'query', required: false, hint: 'e.g. /Shared/Clients', description: 'Restrict audit to this folder.' },
      { key: 'username',      type: 'query', required: false, hint: 'e.g. john.doe', description: 'Filter by user.' },
      { key: 'action',        type: 'query', required: false, hint: 'e.g. download', description: 'Filter by action: download, upload, delete, move, create_link.' },
      { key: 'start_date',    type: 'query', required: false, hint: 'e.g. 2024-01-01', description: 'Start of date range (YYYY-MM-DD).' },
      { key: 'end_date',      type: 'query', required: false, hint: 'e.g. 2024-12-31', description: 'End of date range (YYYY-MM-DD).' },
      { key: 'format',        type: 'query', required: false, hint: 'e.g. json', description: 'Response format: json or csv.' },
    ],
  },
  {
    id: 'audit-login',
    group: 'Audit',
    name: 'Get Login Audit Report',
    method: 'GET',
    baseUrl: 'https://{egnyteDomain}.egnyte.com/pubapi/v1/audit/logins',
    description: 'Returns a log of user login events.',
    params: [
      { key: 'egnyteDomain', type: 'path',  required: true, hint: 'e.g. torrancelearning', description: 'Your Egnyte subdomain.' },
      { key: 'username',      type: 'query', required: false, hint: 'e.g. john.doe', description: 'Filter by user.' },
      { key: 'start_date',    type: 'query', required: false, hint: 'e.g. 2024-01-01', description: 'Start date (YYYY-MM-DD).' },
      { key: 'end_date',      type: 'query', required: false, hint: 'e.g. 2024-12-31', description: 'End date (YYYY-MM-DD).' },
      { key: 'format',        type: 'query', required: false, hint: 'e.g. json', description: 'json or csv.' },
    ],
  },
];
