// Microsoft Graph API — OneDrive
// https://learn.microsoft.com/en-us/graph/api/resources/onedrive
// Base URL: https://graph.microsoft.com/v1.0/
// Includes user lookups since most OneDrive calls need a target userId.

export const onedriveAPIs = [

  // ── USERS ─────────────────────────────────────────────────────────────────
  {
    id: 'users-list',
    group: 'Users',
    name: 'List Users',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/users',
    description: 'Returns all users in the Microsoft 365 tenant.',
    params: [
      { key: 'domain',    type: 'path',  required: true, hint: 'e.g. contoso.com or contoso.onmicrosoft.com', description: 'Your M365 tenant domain.' },
      { key: '$top',      type: 'query', required: false, hint: 'e.g. 999', description: 'Max users per page.' },
      { key: '$select',   type: 'query', required: false, hint: 'e.g. id,displayName,mail,userPrincipalName,accountEnabled', description: 'Fields to return.' },
      { key: '$filter',   type: 'query', required: false, hint: "e.g. accountEnabled eq true", description: 'OData filter.' },
      { key: '$orderby',  type: 'query', required: false, hint: 'e.g. displayName', description: 'Sort field.' },
      { key: '$skiptoken',type: 'query', required: false, hint: 'e.g. <skiptoken from @odata.nextLink>', description: 'Pagination skip token.' },
    ],
  },
  {
    id: 'users-get',
    group: 'Users',
    name: 'Get User',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/users/{userId}',
    description: 'Returns details for a specific user — name, email, sign-in status, roles.',
    params: [
      { key: 'domain',  type: 'path',  required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'userId',  type: 'path',  required: true, hint: 'e.g. user@contoso.com or objectId', description: 'User UPN or object ID.' },
      { key: '$select', type: 'query', required: false, hint: 'e.g. id,displayName,mail,accountEnabled,onPremisesSyncEnabled', description: 'Fields to return.' },
    ],
  },
  {
    id: 'users-filter-name',
    group: 'Users',
    name: 'Filter Users by Display Name',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/users',
    description: "Find users whose displayName starts with a given prefix.",
    params: [
      { key: 'domain',  type: 'path',  required: true, hint: 'e.g. turner.onmicrosoft.com', description: 'Your M365 tenant domain.' },
      { key: '$filter', type: 'query', required: true, hint: "e.g. startswith(displayName,'john')", description: 'OData filter using startswith.' },
      { key: '$top',    type: 'query', required: false, hint: 'e.g. 999', description: 'Max users to return.' },
      { key: '$select', type: 'query', required: false, hint: 'e.g. id,displayName,mail,userPrincipalName', description: 'Fields to return.' },
    ],
  },
  {
    id: 'users-create',
    group: 'Users',
    name: 'Create User',
    method: 'POST',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/users',
    description: 'Creates a new user in the Microsoft 365 tenant.',
    params: [
      { key: 'domain',              type: 'path',  required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'displayName',          type: 'body',  required: true, hint: 'e.g. John Doe', description: 'Display name.' },
      { key: 'userPrincipalName',    type: 'body',  required: true, hint: 'e.g. john.doe@contoso.com', description: 'UPN (login email).' },
      { key: 'mailNickname',         type: 'body',  required: true, hint: 'e.g. johndoe', description: 'Alias (without domain).' },
      { key: 'accountEnabled',       type: 'body',  required: true, hint: 'e.g. true', description: 'Enable the account.' },
      { key: 'passwordProfile.password', type: 'body', required: true, hint: 'e.g. TempPass@1234', description: 'Initial password.' },
      { key: 'passwordProfile.forceChangePasswordNextSignIn', type: 'body', required: false, hint: 'e.g. true', description: 'Force password change on first login.' },
    ],
  },
  {
    id: 'users-update',
    group: 'Users',
    name: 'Update User',
    method: 'PATCH',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/users/{userId}',
    description: 'Updates a user\'s properties — display name, department, job title, block sign-in, etc.',
    params: [
      { key: 'domain',          type: 'path', required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'userId',          type: 'path', required: true, hint: 'e.g. user@contoso.com', description: 'User UPN or object ID.' },
      { key: 'displayName',     type: 'body', required: false, hint: 'e.g. Jane Smith', description: 'New display name.' },
      { key: 'accountEnabled',  type: 'body', required: false, hint: 'e.g. false', description: 'Block sign-in (false) or enable (true).' },
      { key: 'department',      type: 'body', required: false, hint: 'e.g. Sales', description: 'Department.' },
      { key: 'jobTitle',        type: 'body', required: false, hint: 'e.g. Sales Manager', description: 'Job title.' },
    ],
  },
  {
    id: 'users-delete',
    group: 'Users',
    name: 'Delete User',
    method: 'DELETE',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/users/{userId}',
    description: 'Deletes a user from the Microsoft 365 tenant.',
    params: [
      { key: 'domain',  type: 'path', required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'userId',  type: 'path', required: true, hint: 'e.g. user@contoso.com', description: 'User UPN or object ID.' },
    ],
  },

  // ── ONEDRIVE — Drive ──────────────────────────────────────────────────────
  {
    id: 'onedrive-get-my-drive',
    group: 'OneDrive — Drive',
    name: 'Get My Drive',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/me/drive',
    description: 'Returns the current user\'s OneDrive — ID, quota, owner info.',
    params: [],
  },
  {
    id: 'onedrive-get-user-drive',
    group: 'OneDrive — Drive',
    name: 'Get User OneDrive',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/users/{userId}/drive',
    description: 'Returns OneDrive metadata for a specific user — quota, root ID.',
    params: [
      { key: 'domain',  type: 'path', required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'userId',  type: 'path', required: true, hint: 'e.g. user@contoso.com or objectId', description: 'User UPN or object ID.' },
    ],
  },
  {
    id: 'onedrive-get-drive-root',
    group: 'OneDrive — Drive',
    name: 'Get Drive Root Folder',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/users/{userId}/drive/root',
    description: 'Gets the root folder of a user\'s OneDrive — useful to find the root item ID.',
    params: [
      { key: 'domain',  type: 'path', required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'userId',  type: 'path', required: true, hint: 'e.g. 37962f1d-2c04-42ac-86bf-33bddc4c7286', description: 'User object ID.' },
    ],
  },
  {
    id: 'onedrive-list-drives',
    group: 'OneDrive — Drive',
    name: 'List User\'s Drives',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/me/drives',
    description: 'Returns all drives accessible to the current user.',
    params: [],
  },
  {
    id: 'onedrive-get-drive-by-id',
    group: 'OneDrive — Drive',
    name: 'Get Drive by Drive ID',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/drives/{driveId}',
    description: 'Returns metadata for a specific OneDrive by its drive ID.',
    params: [
      { key: 'driveId', type: 'path', required: true, hint: 'e.g. b!Lev00HNSgEaYDTJDSBXZ4-6eZd...', description: 'Drive ID.' },
    ],
  },

  // ── ONEDRIVE — Items ──────────────────────────────────────────────────────
  {
    id: 'onedrive-list-root-children',
    group: 'OneDrive — Items',
    name: 'List Root Folder Children',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/users/{userId}/drive/root/children',
    description: 'Lists all files and folders at the root of a user\'s OneDrive.',
    params: [
      { key: 'userId',  type: 'path',  required: true, hint: 'e.g. c927d158-735f-434d-aab6-df15affee441', description: 'User object ID.' },
      { key: '$select', type: 'query', required: false, hint: 'e.g. id,name,size,folder,file,createdDateTime,lastModifiedDateTime', description: 'Fields to return.' },
      { key: '$top',    type: 'query', required: false, hint: 'e.g. 100', description: 'Max items per page.' },
    ],
  },
  {
    id: 'onedrive-list-item-children',
    group: 'OneDrive — Items',
    name: 'List Drive Item Children',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/users/{userId}/drive/items/{itemId}/children',
    description: 'Lists all files and sub-folders inside a specific OneDrive folder.',
    params: [
      { key: 'userId',  type: 'path',  required: true, hint: 'e.g. c927d158-735f-434d-aab6-df15affee441', description: 'User object ID.' },
      { key: 'itemId',  type: 'path',  required: true, hint: 'e.g. 01YZNLDGXPASWJNZDFDNCZWQ6TTTTMS425  (or root)', description: 'Drive item ID. Use root for the top-level.' },
      { key: '$select', type: 'query', required: false, hint: 'e.g. id,name,size,folder,file,webUrl', description: 'Fields to return.' },
      { key: '$top',    type: 'query', required: false, hint: 'e.g. 100', description: 'Max items per page.' },
    ],
  },
  {
    id: 'onedrive-get-item',
    group: 'OneDrive — Items',
    name: 'Get Drive Item Metadata',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/users/{userId}/drive/items/{itemId}',
    description: 'Returns metadata for a OneDrive file or folder — name, size, type, webUrl, downloadUrl.',
    params: [
      { key: 'domain',  type: 'path',  required: true, hint: 'e.g. turner.onmicrosoft.com', description: 'Your M365 tenant domain.' },
      { key: 'userId',  type: 'path',  required: true, hint: 'e.g. 5f3f4f36-9b0d-4f13-8265-3908034ae9c2', description: 'User object ID.' },
      { key: 'itemId',  type: 'path',  required: true, hint: 'e.g. 01UGZNTNJEAOPJH57XR5BLZWLFB5PKQVVR', description: 'Drive item ID.' },
      { key: '$select', type: 'query', required: false, hint: 'e.g. id,name,size,file,folder,@microsoft.graph.downloadUrl', description: 'Fields to return (include @microsoft.graph.downloadUrl to get download link).' },
    ],
  },
  {
    id: 'onedrive-search-items',
    group: 'OneDrive — Items',
    name: 'Search Drive Items',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/me/drive/search(q=\'{searchText}\')',
    description: 'Searches for files and folders in the current user\'s OneDrive.',
    params: [
      { key: 'searchText', type: 'path',  required: true, hint: 'e.g. invoice', description: 'Text to search for in file names and content.' },
      { key: '$select',    type: 'query', required: false, hint: 'e.g. id,name,webUrl,size,createdDateTime', description: 'Fields to return.' },
      { key: '$top',       type: 'query', required: false, hint: 'e.g. 50', description: 'Max results.' },
    ],
  },
  {
    id: 'onedrive-create-folder',
    group: 'OneDrive — Items',
    name: 'Create Folder (OneDrive)',
    method: 'POST',
    baseUrl: 'https://graph.microsoft.com/v1.0/users/{userId}/drive/items/{parentItemId}/children',
    description: 'Creates a new folder inside an existing OneDrive folder.',
    params: [
      { key: 'userId',        type: 'path', required: true, hint: 'e.g. objectId', description: 'User object ID.' },
      { key: 'parentItemId',  type: 'path', required: true, hint: 'e.g. root or folder item ID', description: 'Parent folder item ID.' },
      { key: 'name',          type: 'body', required: true, hint: 'e.g. New Folder', description: 'New folder name.' },
      { key: 'folder',        type: 'body', required: true, hint: 'e.g. {}', description: 'Empty object — signals this is a folder.' },
      { key: '@microsoft.graph.conflictBehavior', type: 'body', required: false, hint: 'e.g. rename', description: 'Conflict behavior: fail, rename, or replace.' },
    ],
  },
  {
    id: 'onedrive-copy-item',
    group: 'OneDrive — Items',
    name: 'Copy Drive Item',
    method: 'POST',
    baseUrl: 'https://graph.microsoft.com/v1.0/me/drive/items/{itemId}/copy',
    description: 'Asynchronously copies a file or folder to a new location.',
    params: [
      { key: 'itemId',            type: 'path', required: true, hint: 'e.g. item ID to copy', description: 'Source item ID.' },
      { key: 'parentReference.id',type: 'body', required: true, hint: 'e.g. destination folder ID', description: 'Destination folder ID.' },
      { key: 'name',               type: 'body', required: false, hint: 'e.g. Copy of document.docx', description: 'Optional new name for the copy.' },
    ],
  },
  {
    id: 'onedrive-update-item',
    group: 'OneDrive — Items',
    name: 'Update Drive Item (Rename / Move)',
    method: 'PATCH',
    baseUrl: 'https://graph.microsoft.com/v1.0/me/drive/items/{itemId}',
    description: 'Renames or moves a OneDrive item.',
    params: [
      { key: 'itemId',              type: 'path', required: true, hint: 'e.g. item ID', description: 'Drive item ID.' },
      { key: 'name',                type: 'body', required: false, hint: 'e.g. NewName.docx', description: 'New name for the item.' },
      { key: 'parentReference.id',  type: 'body', required: false, hint: 'e.g. destination folder ID', description: 'Move to this folder ID.' },
    ],
  },
  {
    id: 'onedrive-delete-item',
    group: 'OneDrive — Items',
    name: 'Delete Drive Item',
    method: 'DELETE',
    baseUrl: 'https://graph.microsoft.com/v1.0/me/drive/items/{itemId}',
    description: 'Moves a OneDrive item to the recycle bin.',
    params: [
      { key: 'itemId', type: 'path', required: true, hint: 'e.g. drive item ID', description: 'Drive item ID to delete.' },
    ],
  },

  // ── ONEDRIVE — Permissions ────────────────────────────────────────────────
  {
    id: 'onedrive-list-item-permissions',
    group: 'OneDrive — Permissions',
    name: 'List Drive Item Permissions',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/users/{userId}/drive/items/{itemId}/permissions',
    description: 'Returns all sharing and permission entries for a OneDrive file or folder.',
    params: [
      { key: 'domain',  type: 'path', required: true, hint: 'e.g. ufainc.com', description: 'Your M365 tenant domain.' },
      { key: 'userId',  type: 'path', required: true, hint: 'e.g. 32868d6f-c7e0-4edd-99d0-99a51ac001f4', description: 'User object ID.' },
      { key: 'itemId',  type: 'path', required: true, hint: 'e.g. 01DQWIKX3Z5WROGRBT35G3DFFLNZGT47MY', description: 'Drive item ID.' },
    ],
  },
  {
    id: 'onedrive-create-sharing-link',
    group: 'OneDrive — Permissions',
    name: 'Create Sharing Link',
    method: 'POST',
    baseUrl: 'https://graph.microsoft.com/v1.0/me/drive/items/{itemId}/createLink',
    description: 'Creates a sharing link for a OneDrive file or folder.',
    params: [
      { key: 'itemId',     type: 'path', required: true, hint: 'e.g. drive item ID', description: 'Drive item ID.' },
      { key: 'type',       type: 'body', required: true, hint: 'e.g. view', description: 'Link type: view, edit, or embed.' },
      { key: 'scope',      type: 'body', required: false, hint: 'e.g. anonymous', description: 'anonymous or organization.' },
      { key: 'expirationDateTime', type: 'body', required: false, hint: 'e.g. 2025-12-31T00:00:00Z', description: 'Link expiry (ISO 8601).' },
      { key: 'password',   type: 'body', required: false, hint: 'e.g. mypassword', description: 'Optional link password.' },
    ],
  },
  {
    id: 'onedrive-invite',
    group: 'OneDrive — Permissions',
    name: 'Invite (Grant Access)',
    method: 'POST',
    baseUrl: 'https://graph.microsoft.com/v1.0/me/drive/items/{itemId}/invite',
    description: 'Sends an invitation and grants access to a OneDrive item.',
    params: [
      { key: 'itemId',    type: 'path', required: true, hint: 'e.g. drive item ID', description: 'Drive item ID.' },
      { key: 'roles',     type: 'body', required: true, hint: 'e.g. ["read"]', description: 'Roles: read or write.' },
      { key: 'recipients',type: 'body', required: true, hint: 'e.g. [{"email":"user@example.com"}]', description: 'Array of recipient email objects.' },
      { key: 'message',   type: 'body', required: false, hint: 'e.g. Sharing this file with you', description: 'Optional message in the invitation email.' },
      { key: 'sendInvitation', type: 'body', required: false, hint: 'e.g. true', description: 'If true, sends an email notification.' },
    ],
  },
  {
    id: 'onedrive-delete-permission',
    group: 'OneDrive — Permissions',
    name: 'Delete Permission',
    method: 'DELETE',
    baseUrl: 'https://graph.microsoft.com/v1.0/me/drive/items/{itemId}/permissions/{permId}',
    description: 'Removes a specific sharing permission from a OneDrive item.',
    params: [
      { key: 'itemId', type: 'path', required: true, hint: 'e.g. drive item ID', description: 'Drive item ID.' },
      { key: 'permId', type: 'path', required: true, hint: 'e.g. permission ID from list permissions', description: 'Permission ID to remove.' },
    ],
  },
];
