// Full Citrix ShareFile API v3 reference — https://api.sharefile.com/
// Base URL is account-specific: https://{subdomain}.sf-api.com/sf/v3/
//   If you log in at https://mycompany.sharefile.com, your API host is mycompany.sf-api.com
// Protocol: a subset of OData v3 — resource IDs go INSIDE parentheses, e.g. Items(id).
// Auth: OAuth2 Bearer token (Authorization: Bearer <token>).
// NOTE: every operation takes a `subdomain` path param — enter your account subdomain (the part
//       before .sharefile.com), e.g. "mycompany".

export const sharefileAPIs = [

  // ── ITEMS — Read ────────────────────────────────────────────────────────────
  {
    id: 'items-get-home',
    group: 'Items — Read',
    name: 'Get Home Folder',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items',
    description: 'Returns the home folder for the currently authenticated user.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Your ShareFile account subdomain.' },
    ],
  },
  {
    id: 'items-get',
    group: 'Items — Read',
    name: 'Get Item by ID',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})',
    description: 'Returns a single item (File or Folder) by ID. Special IDs: home, favorites, allshared, connectors, box, top.',
    params: [
      { key: 'subdomain',      type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',             type: 'path',  required: true,  hint: 'e.g. fo1a2b3c-... or home', description: 'Item ID or a special alias.' },
      { key: 'includeDeleted', type: 'query', required: false, hint: 'e.g. false', description: 'Include deleted items.' },
      { key: '$expand',        type: 'query', required: false, hint: 'e.g. Children', description: 'OData expand of navigation properties.' },
      { key: '$select',        type: 'query', required: false, hint: 'e.g. Id,Name,FileSizeBytes', description: 'OData field selection.' },
    ],
  },
  {
    id: 'items-children',
    group: 'Items — Read',
    name: 'List Folder Children',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})/Children',
    description: 'Returns the files and sub-folders inside a folder.',
    params: [
      { key: 'subdomain',      type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',             type: 'path',  required: true,  hint: 'e.g. fo1a2b3c-... or home', description: 'Folder ID.' },
      { key: 'includeDeleted', type: 'query', required: false, hint: 'e.g. false', description: 'Include deleted children.' },
      { key: 'orderingMode',   type: 'query', required: false, hint: 'e.g. sortByFileName', description: 'Server-side ordering mode.' },
      { key: '$select',        type: 'query', required: false, hint: 'e.g. Id,Name,CreationDate', description: 'OData field selection.' },
      { key: '$orderby',       type: 'query', required: false, hint: 'e.g. Name asc', description: 'OData ordering.' },
    ],
  },
  {
    id: 'items-by-path',
    group: 'Items — Read',
    name: 'Get Item by Path',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items/ByPath',
    description: 'Fetches an item using its full file path from the account root.',
    params: [
      { key: 'subdomain', type: 'path',  required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'path',      type: 'query', required: true, hint: 'e.g. /Personal Folders/Reports/q4.pdf', description: 'Full path to the item.' },
    ],
  },
  {
    id: 'items-by-path-relative',
    group: 'Items — Read',
    name: 'Get Item by Relative Path',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})/ByPath',
    description: 'Gets an item by a path relative to the specified parent folder.',
    params: [
      { key: 'subdomain', type: 'path',  required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path',  required: true, hint: 'e.g. fo1a2b3c-...', description: 'Parent folder ID.' },
      { key: 'path',      type: 'query', required: true, hint: 'e.g. Reports/q4.pdf', description: 'Relative path from the parent.' },
    ],
  },
  {
    id: 'items-parent',
    group: 'Items — Read',
    name: 'Get Item Parent',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})/Parent',
    description: 'Returns the parent folder of an item.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path', required: true, hint: 'e.g. fi1a2b3c-...', description: 'Item ID.' },
    ],
  },
  {
    id: 'items-breadcrumbs',
    group: 'Items — Read',
    name: 'Get Item Breadcrumbs',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})/Breadcrumbs',
    description: 'Returns the path (breadcrumb trail) from the item back to the root.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path', required: true, hint: 'e.g. fi1a2b3c-...', description: 'Item ID.' },
    ],
  },
  {
    id: 'items-treeview',
    group: 'Items — Read',
    name: 'Get Folder Tree View',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})/TreeView',
    description: 'Returns the folder structure for tree navigation in a UI.',
    params: [
      { key: 'subdomain', type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path',  required: true,  hint: 'e.g. fo1a2b3c-...', description: 'Folder ID.' },
      { key: 'treeMode',  type: 'query', required: false, hint: 'e.g. 1', description: 'Tree traversal mode.' },
      { key: 'sourceId',  type: 'query', required: false, hint: 'e.g. fo1a2b3c-...', description: 'Source item to expand toward.' },
    ],
  },
  {
    id: 'items-thumbnail',
    group: 'Items — Read',
    name: 'Get Item Thumbnail',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})/Thumbnail',
    description: 'Returns a link to a thumbnail image for the item.',
    params: [
      { key: 'subdomain', type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path',  required: true,  hint: 'e.g. fi1a2b3c-...', description: 'Item ID.' },
      { key: 'size',      type: 'query', required: false, hint: 'e.g: 100', description: 'Thumbnail size in pixels.' },
      { key: 'redirect',  type: 'query', required: false, hint: 'e.g. false', description: 'Redirect to the image instead of returning a link.' },
    ],
  },
  {
    id: 'items-access-info',
    group: 'Items — Read',
    name: 'Get Item Access Info',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})/Info',
    description: 'Returns the access controls the authenticated user has on the item.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path', required: true, hint: 'e.g. fi1a2b3c-...', description: 'Item ID.' },
    ],
  },

  // ── ITEMS — Write ───────────────────────────────────────────────────────────
  {
    id: 'items-create-folder',
    group: 'Items — Write',
    name: 'Create Folder',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({parentid})/Folder',
    description: 'Creates a new folder inside the specified parent folder.',
    params: [
      { key: 'subdomain',   type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'parentid',    type: 'path',  required: true,  hint: 'e.g. fo1a2b3c-... or home', description: 'Parent folder ID.' },
      { key: 'overwrite',   type: 'query', required: false, hint: 'e.g. false', description: 'Overwrite an existing folder of the same name.' },
      { key: 'Name',        type: 'body',  required: true,  hint: 'e.g. Q4 Reports', description: 'Name of the new folder.' },
      { key: 'Description', type: 'body',  required: false, hint: 'e.g. Quarterly reports', description: 'Folder description.' },
    ],
  },
  {
    id: 'items-update',
    group: 'Items — Write',
    name: 'Update / Rename / Move Item',
    method: 'PATCH',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})',
    description: 'Updates an item — rename, change description, expiration, move (via Parent), or change Zone.',
    params: [
      { key: 'subdomain',   type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',          type: 'path',  required: true,  hint: 'e.g. fi1a2b3c-...', description: 'Item ID.' },
      { key: 'overwrite',   type: 'query', required: false, hint: 'e.g. false', description: 'Overwrite conflicts.' },
      { key: 'Name',        type: 'body',  required: false, hint: 'e.g. renamed.pdf', description: 'New name.' },
      { key: 'Description', type: 'body',  required: false, hint: 'e.g. Updated report', description: 'New description.' },
      { key: 'Parent.Id',   type: 'body',  required: false, hint: 'e.g. fo9z8y7x-...', description: 'New parent folder ID (to move the item).' },
    ],
  },
  {
    id: 'items-copy',
    group: 'Items — Write',
    name: 'Copy Item',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})/Copy',
    description: 'Copies an item to a target folder.',
    params: [
      { key: 'subdomain', type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path',  required: true,  hint: 'e.g. fi1a2b3c-...', description: 'Item ID to copy.' },
      { key: 'targetid',  type: 'query', required: true,  hint: 'e.g. fo9z8y7x-...', description: 'Destination folder ID.' },
      { key: 'overwrite', type: 'query', required: false, hint: 'e.g. false', description: 'Overwrite if a same-named item exists.' },
    ],
  },
  {
    id: 'items-delete',
    group: 'Items — Write',
    name: 'Delete Item',
    method: 'DELETE',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})',
    description: 'Deletes an item (moves it to recycle bin, or a specific version).',
    params: [
      { key: 'subdomain',     type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',            type: 'path',  required: true,  hint: 'e.g. fi1a2b3c-...', description: 'Item ID to delete.' },
      { key: 'singleversion', type: 'query', required: false, hint: 'e.g. false', description: 'Delete only the specified version.' },
      { key: 'forceSync',     type: 'query', required: false, hint: 'e.g. false', description: 'Force synchronous deletion.' },
    ],
  },
  {
    id: 'items-bulk-delete',
    group: 'Items — Write',
    name: 'Bulk Delete Items',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({parentid})/BulkDelete',
    description: 'Deletes multiple items within a folder in one call.',
    params: [
      { key: 'subdomain',         type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'parentid',          type: 'path',  required: true,  hint: 'e.g. fo1a2b3c-...', description: 'Parent folder ID.' },
      { key: 'deletePermanently', type: 'query', required: false, hint: 'e.g. false', description: 'Permanently delete (skip recycle bin).' },
      { key: 'ids',               type: 'body',  required: true,  hint: 'e.g. ["fi111...","fi222..."]', description: 'Array of item IDs to delete.' },
    ],
  },
  {
    id: 'items-create-note',
    group: 'Items — Write',
    name: 'Create Note',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({parentid})/Note',
    description: 'Creates a new note item inside a folder.',
    params: [
      { key: 'subdomain', type: 'path', required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'parentid',  type: 'path', required: true,  hint: 'e.g. fo1a2b3c-...', description: 'Parent folder ID.' },
      { key: 'Name',      type: 'body', required: true,  hint: 'e.g. Reminder', description: 'Note title.' },
      { key: 'Description', type: 'body', required: false, hint: 'e.g. Notes body text', description: 'Note content.' },
    ],
  },
  {
    id: 'items-create-link',
    group: 'Items — Write',
    name: 'Create Web Link',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({parentid})/Link',
    description: 'Creates a web link (URL bookmark) item inside a folder.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'parentid',  type: 'path', required: true, hint: 'e.g. fo1a2b3c-...', description: 'Parent folder ID.' },
      { key: 'Uri',       type: 'body', required: true, hint: 'e.g. https://example.com', description: 'Target URL.' },
      { key: 'Name',      type: 'body', required: false, hint: 'e.g. Example', description: 'Link display name.' },
    ],
  },

  // ── ITEMS — Upload & Download ───────────────────────────────────────────────
  {
    id: 'items-upload',
    group: 'Items — Upload & Download',
    name: 'Request Upload Specification',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})/Upload2',
    description: 'Prepares an upload — returns the ChunkUri and upload spec. Actual bytes are POSTed to the returned ChunkUri.',
    params: [
      { key: 'subdomain', type: 'path', required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path', required: true,  hint: 'e.g. fo1a2b3c-...', description: 'Destination folder ID.' },
      { key: 'Method',    type: 'body', required: true,  hint: 'e.g. Standard', description: 'Upload method: Standard, Streamed, or Threaded.' },
      { key: 'FileName',  type: 'body', required: true,  hint: 'e.g. report.pdf', description: 'Name of the file to upload.' },
      { key: 'FileSize',  type: 'body', required: false, hint: 'e.g. 1048576', description: 'File size in bytes.' },
      { key: 'Overwrite', type: 'body', required: false, hint: 'e.g. false', description: 'Overwrite an existing file.' },
    ],
  },
  {
    id: 'items-download',
    group: 'Items — Upload & Download',
    name: 'Download Item',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})/Download',
    description: 'Downloads a file, or a folder as a ZIP archive. Returns a download URL unless redirect=true.',
    params: [
      { key: 'subdomain',          type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',                 type: 'path',  required: true,  hint: 'e.g. fi1a2b3c-...', description: 'Item ID to download.' },
      { key: 'redirect',           type: 'query', required: false, hint: 'e.g. false', description: 'If true, 302-redirects to the file; if false returns a link.' },
      { key: 'includeAllVersions', type: 'query', required: false, hint: 'e.g. false', description: 'Include all versions (folder ZIP).' },
    ],
  },
  {
    id: 'items-bulk-download',
    group: 'Items — Upload & Download',
    name: 'Bulk Download',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({parentid})/BulkDownload',
    description: 'Downloads multiple items as a single ZIP archive.',
    params: [
      { key: 'subdomain', type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'parentid',  type: 'path',  required: true,  hint: 'e.g. fo1a2b3c-...', description: 'Parent folder ID.' },
      { key: 'redirect',  type: 'query', required: false, hint: 'e.g. false', description: 'Redirect to the archive URL.' },
      { key: 'ids',       type: 'body',  required: true,  hint: 'e.g. ["fi111...","fi222..."]', description: 'Array of item IDs to include.' },
    ],
  },

  // ── ITEMS — Search ──────────────────────────────────────────────────────────
  {
    id: 'items-search',
    group: 'Items — Search',
    name: 'Search (Account-wide)',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items/Search',
    description: 'Searches items across the entire account matching a query string.',
    params: [
      { key: 'subdomain',      type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'query',          type: 'query', required: true,  hint: 'e.g. invoice 2024', description: 'Search query.' },
      { key: 'maxResults',     type: 'query', required: false, hint: 'e.g. 50', description: 'Maximum results to return.' },
      { key: 'skip',           type: 'query', required: false, hint: 'e.g. 0', description: 'Number of results to skip (paging).' },
      { key: 'homeFolderOnly', type: 'query', required: false, hint: 'e.g. false', description: 'Restrict search to the home folder.' },
    ],
  },
  {
    id: 'items-search-folder',
    group: 'Items — Search',
    name: 'Search Within Folder',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})/Search',
    description: 'Searches items within a specific folder.',
    params: [
      { key: 'subdomain',  type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',         type: 'path',  required: true,  hint: 'e.g. fo1a2b3c-...', description: 'Folder ID to search in.' },
      { key: 'query',      type: 'query', required: true,  hint: 'e.g. contract', description: 'Search query.' },
      { key: 'maxResults', type: 'query', required: false, hint: 'e.g. 50', description: 'Maximum results.' },
      { key: 'skip',       type: 'query', required: false, hint: 'e.g. 0', description: 'Results to skip.' },
    ],
  },
  {
    id: 'items-advanced-search',
    group: 'Items — Search',
    name: 'Advanced Search',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items/AdvancedSearch',
    description: 'Runs a multi-criteria search with query, paging and sort objects.',
    params: [
      { key: 'subdomain', type: 'path', required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'Query',     type: 'body', required: true,  hint: 'e.g. {"SearchQuery":"report","ItemType":"File"}', description: 'Query object.' },
      { key: 'Paging',    type: 'body', required: false, hint: 'e.g. {"Count":50,"Skip":0}', description: 'Paging object.' },
      { key: 'Sort',      type: 'body', required: false, hint: 'e.g. {"SortBy":"Relevance"}', description: 'Sort object.' },
    ],
  },

  // ── ITEMS — Recycle Bin ─────────────────────────────────────────────────────
  {
    id: 'items-deleted-children',
    group: 'Items — Recycle Bin',
    name: 'List Deleted Children',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({parentid})/DeletedChildren',
    description: 'Lists recoverable (deleted) items within a folder.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'parentid',  type: 'path', required: true, hint: 'e.g. fo1a2b3c-...', description: 'Parent folder ID.' },
    ],
  },
  {
    id: 'items-bulk-restore',
    group: 'Items — Recycle Bin',
    name: 'Bulk Restore Items',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items/BulkRestore',
    description: 'Restores multiple deleted/expired items.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'ids',       type: 'body', required: true, hint: 'e.g. ["fi111...","fi222..."]', description: 'Array of item IDs to restore.' },
    ],
  },
  {
    id: 'items-bulk-delete-permanently',
    group: 'Items — Recycle Bin',
    name: 'Bulk Delete Permanently',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items/BulkDeletePermanently',
    description: 'Permanently removes multiple items. Cannot be undone.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'ids',       type: 'body', required: true, hint: 'e.g. ["fi111...","fi222..."]', description: 'Array of item IDs.' },
    ],
  },

  // ── USERS ───────────────────────────────────────────────────────────────────
  {
    id: 'users-get-current',
    group: 'Users',
    name: 'Get Current User',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Users',
    description: 'Returns the currently authenticated user (when called with no id/email filter).',
    params: [
      { key: 'subdomain',    type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'emailaddress', type: 'query', required: false, hint: 'e.g. jane@company.com', description: 'Look up a user by email instead.' },
    ],
  },
  {
    id: 'users-get',
    group: 'Users',
    name: 'Get User by ID',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Users({id})',
    description: 'Returns a specific user by ID.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path', required: true, hint: 'e.g. u1a2b3c4-...', description: 'User ID.' },
    ],
  },
  {
    id: 'users-info',
    group: 'Users',
    name: 'Get Current User Info',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Users/Info',
    description: 'Returns information about the currently authenticated user.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
    ],
  },
  {
    id: 'users-home-folder',
    group: 'Users',
    name: 'Get User Home Folder',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Users/HomeFolder',
    description: 'Returns the home folder of the current (or specified) user.',
    params: [
      { key: 'subdomain', type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'query', required: false, hint: 'e.g. u1a2b3c4-...', description: 'Optional user ID.' },
    ],
  },
  {
    id: 'users-all-shared-folders',
    group: 'Users',
    name: 'List Shared Folders',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Users/AllSharedFolders',
    description: 'Returns the list of shared folders the authenticated user can access.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
    ],
  },
  {
    id: 'users-groups',
    group: 'Users',
    name: 'List User Groups',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Users({id})/Groups',
    description: 'Returns all groups the specified user belongs to.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path', required: true, hint: 'e.g. u1a2b3c4-...', description: 'User ID.' },
    ],
  },
  {
    id: 'users-create-client',
    group: 'Users',
    name: 'Create Client User',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Users',
    description: 'Creates a new client (external) user.',
    params: [
      { key: 'subdomain',   type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'notify',      type: 'query', required: false, hint: 'e.g. true', description: 'Send an activation email.' },
      { key: 'Email',       type: 'body',  required: true,  hint: 'e.g. client@ext.com', description: 'Client email address.' },
      { key: 'FirstName',   type: 'body',  required: true,  hint: 'e.g. John', description: 'First name.' },
      { key: 'LastName',    type: 'body',  required: true,  hint: 'e.g. Doe', description: 'Last name.' },
      { key: 'Company',     type: 'body',  required: false, hint: 'e.g. Acme Inc', description: 'Company name.' },
      { key: 'DefaultZone.Id', type: 'body', required: false, hint: 'e.g. z1a2b3c4-...', description: 'Default storage zone ID.' },
    ],
  },
  {
    id: 'users-create-employee',
    group: 'Users',
    name: 'Create Employee User',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Users/AccountUser',
    description: 'Creates a new employee (internal) user.',
    params: [
      { key: 'subdomain',            type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'notify',               type: 'query', required: false, hint: 'e.g. true', description: 'Send an activation email.' },
      { key: 'Email',                type: 'body',  required: true,  hint: 'e.g. emp@company.com', description: 'Employee email.' },
      { key: 'FirstName',            type: 'body',  required: true,  hint: 'e.g. Jane', description: 'First name.' },
      { key: 'LastName',             type: 'body',  required: true,  hint: 'e.g. Smith', description: 'Last name.' },
      { key: 'StorageQuotaLimitGB',  type: 'body',  required: false, hint: 'e.g. 100', description: 'Storage quota in GB.' },
    ],
  },
  {
    id: 'users-update',
    group: 'Users',
    name: 'Update User',
    method: 'PATCH',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Users({id})',
    description: 'Updates a user — name, email, company, disabled state, default zone.',
    params: [
      { key: 'subdomain',  type: 'path', required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',         type: 'path', required: true,  hint: 'e.g. u1a2b3c4-...', description: 'User ID.' },
      { key: 'FirstName',  type: 'body', required: false, hint: 'e.g. Jane', description: 'New first name.' },
      { key: 'LastName',   type: 'body', required: false, hint: 'e.g. Doe', description: 'New last name.' },
      { key: 'Company',    type: 'body', required: false, hint: 'e.g. Acme Inc', description: 'New company.' },
      { key: 'Email',      type: 'body', required: false, hint: 'e.g. new@company.com', description: 'New email address.' },
      { key: 'IsDisabled', type: 'body', required: false, hint: 'e.g. true', description: 'Disable/enable the account.' },
    ],
  },
  {
    id: 'users-delete',
    group: 'Users',
    name: 'Delete User',
    method: 'DELETE',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Users({id})',
    description: 'Deletes a user account, optionally reassigning their items and groups.',
    params: [
      { key: 'subdomain',        type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',               type: 'path',  required: true,  hint: 'e.g. u1a2b3c4-...', description: 'User ID to delete.' },
      { key: 'completely',       type: 'query', required: false, hint: 'e.g. false', description: 'Permanently delete the user.' },
      { key: 'itemsReassignTo',  type: 'query', required: false, hint: 'e.g. u9z8y7x6-...', description: 'User ID to reassign items to.' },
      { key: 'groupsReassignTo', type: 'query', required: false, hint: 'e.g. u9z8y7x6-...', description: 'User ID to reassign group memberships to.' },
    ],
  },

  // ── GROUPS (Distribution Groups) ────────────────────────────────────────────
  {
    id: 'groups-list',
    group: 'Groups',
    name: 'List Groups',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Groups',
    description: 'Returns all distribution groups the user has permission to view.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
    ],
  },
  {
    id: 'groups-get',
    group: 'Groups',
    name: 'Get Group',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Groups({id})',
    description: 'Returns a specific distribution group by ID.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path', required: true, hint: 'e.g. g1a2b3c4-...', description: 'Group ID.' },
    ],
  },
  {
    id: 'groups-create',
    group: 'Groups',
    name: 'Create Group',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Groups',
    description: 'Creates a new distribution group.',
    params: [
      { key: 'subdomain', type: 'path', required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'Name',      type: 'body', required: true,  hint: 'e.g. Engineering', description: 'Group name.' },
      { key: 'IsShared',  type: 'body', required: false, hint: 'e.g. true', description: 'Whether the group is shared with the account.' },
    ],
  },
  {
    id: 'groups-update',
    group: 'Groups',
    name: 'Update Group',
    method: 'PATCH',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Groups({id})',
    description: 'Updates a group — name or shared status.',
    params: [
      { key: 'subdomain', type: 'path', required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path', required: true,  hint: 'e.g. g1a2b3c4-...', description: 'Group ID.' },
      { key: 'Name',      type: 'body', required: false, hint: 'e.g. Engineering Team', description: 'New group name.' },
      { key: 'IsShared',  type: 'body', required: false, hint: 'e.g. true', description: 'New shared status.' },
    ],
  },
  {
    id: 'groups-delete',
    group: 'Groups',
    name: 'Delete Group',
    method: 'DELETE',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Groups({id})',
    description: 'Deletes a distribution group.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path', required: true, hint: 'e.g. g1a2b3c4-...', description: 'Group ID.' },
    ],
  },
  {
    id: 'groups-list-contacts',
    group: 'Groups',
    name: 'List Group Contacts',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Groups({id})/Contacts',
    description: 'Returns the members (contacts) of a group.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path', required: true, hint: 'e.g. g1a2b3c4-...', description: 'Group ID.' },
    ],
  },
  {
    id: 'groups-add-contacts',
    group: 'Groups',
    name: 'Add Group Contacts',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Groups({id})/Contacts',
    description: 'Adds members to a group by email or user ID.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path', required: true, hint: 'e.g. g1a2b3c4-...', description: 'Group ID.' },
      { key: 'Email',     type: 'body', required: false, hint: 'e.g. jane@company.com', description: 'Contact email to add.' },
    ],
  },
  {
    id: 'groups-remove-contacts',
    group: 'Groups',
    name: 'Remove Group Contacts',
    method: 'DELETE',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Groups({id})/Contacts',
    description: 'Removes members from a group by email or ID.',
    params: [
      { key: 'subdomain', type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path',  required: true,  hint: 'e.g. g1a2b3c4-...', description: 'Group ID.' },
      { key: 'contactid', type: 'query', required: false, hint: 'e.g. c1a2b3c4-...', description: 'Contact ID to remove.' },
    ],
  },

  // ── SHARES ──────────────────────────────────────────────────────────────────
  {
    id: 'shares-list',
    group: 'Shares',
    name: 'List Shares',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Shares',
    description: 'Returns all outstanding shares for the authenticated user.',
    params: [
      { key: 'subdomain',      type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'includeExpired', type: 'query', required: false, hint: 'e.g. true', description: 'Include expired shares.' },
    ],
  },
  {
    id: 'shares-get',
    group: 'Shares',
    name: 'Get Share',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Shares({id})',
    description: 'Returns a single share by ID.',
    params: [
      { key: 'subdomain',      type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',             type: 'path',  required: true,  hint: 'e.g. s1a2b3c4-...', description: 'Share ID.' },
      { key: 'includeExpired', type: 'query', required: false, hint: 'e.g. false', description: 'Include if expired.' },
    ],
  },
  {
    id: 'shares-items',
    group: 'Shares',
    name: 'List Share Items',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Shares({id})/Items',
    description: 'Lists the files and folders included in a send share.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path', required: true, hint: 'e.g. s1a2b3c4-...', description: 'Share ID.' },
    ],
  },
  {
    id: 'shares-recipients',
    group: 'Shares',
    name: 'List Share Recipients',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Shares({id})/Recipients',
    description: 'Lists all recipients of a share.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path', required: true, hint: 'e.g. s1a2b3c4-...', description: 'Share ID.' },
    ],
  },
  {
    id: 'shares-create',
    group: 'Shares',
    name: 'Create Share',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Shares',
    description: 'Creates a new send or request share.',
    params: [
      { key: 'subdomain',       type: 'path', required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'ShareType',       type: 'body', required: true,  hint: 'e.g. Send', description: 'Send or Request.' },
      { key: 'Title',           type: 'body', required: false, hint: 'e.g. Q4 Files', description: 'Share title.' },
      { key: 'Items',           type: 'body', required: false, hint: 'e.g. [{"Id":"fi111..."}]', description: 'Items to share (Send shares).' },
      { key: 'ExpirationDate',  type: 'body', required: false, hint: 'e.g. 2026-12-31T00:00:00Z', description: 'Expiration date (ISO 8601).' },
      { key: 'RequireLogin',    type: 'body', required: false, hint: 'e.g. false', description: 'Require recipients to log in.' },
    ],
  },
  {
    id: 'shares-send',
    group: 'Shares',
    name: 'Send Share (Email Files)',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Shares/Send',
    description: 'Sends files by email to recipients (creates a send share and emails it).',
    params: [
      { key: 'subdomain', type: 'path', required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'Items',     type: 'body', required: true,  hint: 'e.g. ["fi111...","fi222..."]', description: 'Array of item IDs to send.' },
      { key: 'Emails',    type: 'body', required: true,  hint: 'e.g. ["a@x.com","b@y.com"]', description: 'Recipient email addresses.' },
      { key: 'Subject',   type: 'body', required: false, hint: 'e.g. Files for review', description: 'Email subject.' },
      { key: 'Body',      type: 'body', required: false, hint: 'e.g. Please review these.', description: 'Email body.' },
      { key: 'ExpirationDays', type: 'body', required: false, hint: 'e.g. 7', description: 'Days until the link expires.' },
    ],
  },
  {
    id: 'shares-request',
    group: 'Shares',
    name: 'Request Share (Request Files)',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Shares/Request',
    description: 'Sends an upload request email, asking recipients to upload files to a folder.',
    params: [
      { key: 'subdomain', type: 'path', required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'FolderId',  type: 'body', required: true,  hint: 'e.g. fo1a2b3c-...', description: 'Destination folder for uploads.' },
      { key: 'Emails',    type: 'body', required: true,  hint: 'e.g. ["a@x.com"]', description: 'Recipient email addresses.' },
      { key: 'Subject',   type: 'body', required: false, hint: 'e.g. Please upload', description: 'Email subject.' },
      { key: 'Body',      type: 'body', required: false, hint: 'e.g. Upload your docs here.', description: 'Email body.' },
    ],
  },
  {
    id: 'shares-update',
    group: 'Shares',
    name: 'Update Share',
    method: 'PATCH',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Shares({id})',
    description: 'Updates properties of an existing share.',
    params: [
      { key: 'subdomain',      type: 'path', required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',             type: 'path', required: true,  hint: 'e.g. s1a2b3c4-...', description: 'Share ID.' },
      { key: 'Title',          type: 'body', required: false, hint: 'e.g. Updated title', description: 'New title.' },
      { key: 'ExpirationDate', type: 'body', required: false, hint: 'e.g. 2026-12-31T00:00:00Z', description: 'New expiration date.' },
    ],
  },
  {
    id: 'shares-delete',
    group: 'Shares',
    name: 'Delete Share',
    method: 'DELETE',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Shares({id})',
    description: 'Removes a share.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path', required: true, hint: 'e.g. s1a2b3c4-...', description: 'Share ID.' },
    ],
  },

  // ── ACCESS CONTROLS ─────────────────────────────────────────────────────────
  {
    id: 'accesscontrols-list',
    group: 'Access Controls',
    name: 'List Item Access Controls',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})/AccessControls',
    description: 'Returns the access control list (permissions) for a folder.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path', required: true, hint: 'e.g. fo1a2b3c-...', description: 'Item (folder) ID.' },
    ],
  },
  {
    id: 'accesscontrols-get',
    group: 'Access Controls',
    name: 'Get Access Control',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/AccessControls(principalid={principalid},itemid={itemid})',
    description: 'Returns a single access control entry for an item and principal.',
    params: [
      { key: 'subdomain',   type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'principalid', type: 'path', required: true, hint: 'e.g. u1a2b3c4-...', description: 'User or group (principal) ID.' },
      { key: 'itemid',      type: 'path', required: true, hint: 'e.g. fo1a2b3c-...', description: 'Item ID.' },
    ],
  },
  {
    id: 'accesscontrols-create',
    group: 'Access Controls',
    name: 'Create Access Control',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})/AccessControls',
    description: 'Grants a principal access to a folder.',
    params: [
      { key: 'subdomain',         type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',                type: 'path',  required: true,  hint: 'e.g. fo1a2b3c-...', description: 'Folder ID.' },
      { key: 'recursive',         type: 'query', required: false, hint: 'e.g. false', description: 'Apply to sub-folders recursively.' },
      { key: 'Principal.Id',      type: 'body',  required: true,  hint: 'e.g. u1a2b3c4-...', description: 'User or group ID to grant access.' },
      { key: 'CanUpload',         type: 'body',  required: false, hint: 'e.g. true', description: 'Allow uploading.' },
      { key: 'CanDownload',       type: 'body',  required: false, hint: 'e.g. true', description: 'Allow downloading.' },
      { key: 'CanView',           type: 'body',  required: false, hint: 'e.g. true', description: 'Allow viewing.' },
      { key: 'CanDelete',         type: 'body',  required: false, hint: 'e.g. false', description: 'Allow deleting.' },
      { key: 'CanManagePermissions', type: 'body', required: false, hint: 'e.g. false', description: 'Allow managing permissions.' },
    ],
  },
  {
    id: 'accesscontrols-update',
    group: 'Access Controls',
    name: 'Update Access Control',
    method: 'PATCH',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Items({id})/AccessControls',
    description: 'Updates an existing access control on a folder.',
    params: [
      { key: 'subdomain',    type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',           type: 'path',  required: true,  hint: 'e.g. fo1a2b3c-...', description: 'Folder ID.' },
      { key: 'recursive',    type: 'query', required: false, hint: 'e.g. false', description: 'Apply recursively.' },
      { key: 'Principal.Id', type: 'body',  required: true,  hint: 'e.g. u1a2b3c4-...', description: 'Principal ID.' },
      { key: 'CanUpload',    type: 'body',  required: false, hint: 'e.g. true', description: 'Allow uploading.' },
      { key: 'CanDownload',  type: 'body',  required: false, hint: 'e.g. true', description: 'Allow downloading.' },
    ],
  },
  {
    id: 'accesscontrols-delete',
    group: 'Access Controls',
    name: 'Delete Access Control',
    method: 'DELETE',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/AccessControls(principalid={principalid},itemid={itemid})',
    description: 'Revokes a principal\'s access to an item.',
    params: [
      { key: 'subdomain',   type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'principalid', type: 'path', required: true, hint: 'e.g. u1a2b3c4-...', description: 'Principal ID.' },
      { key: 'itemid',      type: 'path', required: true, hint: 'e.g. fo1a2b3c-...', description: 'Item ID.' },
    ],
  },

  // ── ZONES ───────────────────────────────────────────────────────────────────
  {
    id: 'zones-list',
    group: 'Zones',
    name: 'List Zones',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Zones',
    description: 'Returns the storage zones accessible to the authenticated user.',
    params: [
      { key: 'subdomain',       type: 'path',  required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'includeDisabled', type: 'query', required: false, hint: 'e.g. false', description: 'Include disabled zones.' },
    ],
  },
  {
    id: 'zones-get',
    group: 'Zones',
    name: 'Get Zone',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Zones({id})',
    description: 'Returns a single storage zone by ID.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'id',        type: 'path', required: true, hint: 'e.g. z1a2b3c4-...', description: 'Zone ID.' },
    ],
  },

  // ── ACCOUNT & CAPABILITIES ──────────────────────────────────────────────────
  {
    id: 'accounts-get',
    group: 'Account',
    name: 'Get Account Info',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Accounts',
    description: 'Returns information about the current ShareFile account.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
    ],
  },
  {
    id: 'capabilities-list',
    group: 'Account',
    name: 'List Capabilities',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Capabilities',
    description: 'Returns the list of capabilities enabled for the account.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
    ],
  },
  {
    id: 'sessions-get',
    group: 'Account',
    name: 'Get Session',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Sessions',
    description: 'Returns information about the current API session.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
    ],
  },

  // ── FAVORITES ───────────────────────────────────────────────────────────────
  {
    id: 'favorites-list',
    group: 'Favorites',
    name: 'List Favorites',
    method: 'GET',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Favorites',
    description: 'Returns the current user\'s favorite items.',
    params: [
      { key: 'subdomain', type: 'path', required: true, hint: 'e.g. mycompany', description: 'Account subdomain.' },
    ],
  },
  {
    id: 'favorites-create',
    group: 'Favorites',
    name: 'Add Favorite',
    method: 'POST',
    baseUrl: 'https://{subdomain}.sf-api.com/sf/v3/Favorites',
    description: 'Marks an item as a favorite for the current user.',
    params: [
      { key: 'subdomain', type: 'path', required: true,  hint: 'e.g. mycompany', description: 'Account subdomain.' },
      { key: 'Item.Id',   type: 'body', required: true,  hint: 'e.g. fi1a2b3c-...', description: 'Item ID to favorite.' },
    ],
  },
];
