// Full Microsoft Graph API — SharePoint
// https://learn.microsoft.com/en-us/graph/api/resources/sharepoint
// Base URL: https://graph.microsoft.com/v1.0/
// For personal OneDrive storage, see onedrive.js.

export const sharepointAPIs = [

  // ── GROUPS ────────────────────────────────────────────────────────────────
  {
    id: 'groups-list',
    group: 'Groups',
    name: 'List Groups',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/groups',
    description: 'Returns all Microsoft 365 and security groups in the tenant.',
    params: [
      { key: 'domain',   type: 'path',  required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: '$top',     type: 'query', required: false, hint: 'e.g. 999', description: 'Max groups to return.' },
      { key: '$filter',  type: 'query', required: false, hint: "e.g. groupTypes/any(c:c eq 'Unified')", description: 'OData filter.' },
      { key: '$select',  type: 'query', required: false, hint: 'e.g. id,displayName,mail,groupTypes', description: 'Fields to return.' },
    ],
  },
  {
    id: 'groups-get',
    group: 'Groups',
    name: 'Get Group',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/groups/{groupId}',
    description: 'Returns details for a specific group.',
    params: [
      { key: 'domain',  type: 'path',  required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'groupId', type: 'path',  required: true, hint: 'e.g. 9e4f9d4b-8a6c-4b77-a123-...',  description: 'Group object ID.' },
      { key: '$select', type: 'query', required: false, hint: 'e.g. id,displayName,mail,members', description: 'Fields to return.' },
    ],
  },
  {
    id: 'groups-list-members',
    group: 'Groups',
    name: 'List Group Members',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/groups/{groupId}/members',
    description: 'Returns all members of a specific Microsoft 365 or security group.',
    params: [
      { key: 'domain',  type: 'path', required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'groupId', type: 'path', required: true, hint: 'e.g. 9e4f9d4b-8a6c-4b77-...', description: 'Group object ID.' },
    ],
  },
  {
    id: 'groups-list-drives',
    group: 'Groups',
    name: 'List Group Drives (Teams Sites)',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/groups/{groupId}/drives',
    description: 'Returns document library drives associated with a Microsoft 365 group (Teams/SharePoint).',
    params: [
      { key: 'domain',  type: 'path', required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'groupId', type: 'path', required: true, hint: 'e.g. 9e4f9d4b-8a6c-4b77-...', description: 'Group object ID.' },
    ],
  },

  // ── SHAREPOINT — SITES ────────────────────────────────────────────────────
  {
    id: 'sites-list',
    group: 'SharePoint — Sites',
    name: 'List Sites',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/sites',
    description: 'Returns all SharePoint sites in the tenant.',
    params: [
      { key: 'domain',  type: 'path',  required: true, hint: 'e.g. nanoporetech.com', description: 'Your M365 tenant domain.' },
      { key: '$select', type: 'query', required: false, hint: 'e.g. id,displayName,webUrl', description: 'Fields to return.' },
    ],
  },
  {
    id: 'sites-get',
    group: 'SharePoint — Sites',
    name: 'Get Site',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/sites/{siteId}',
    description: 'Returns details for a specific SharePoint site.',
    params: [
      { key: 'domain',  type: 'path',  required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'siteId',  type: 'path',  required: true, hint: 'e.g. a0de512f-edb4-4337-8fa5-aff528f0dc87', description: 'SharePoint site ID.' },
      { key: '$select', type: 'query', required: false, hint: 'e.g. id,displayName,webUrl,createdDateTime', description: 'Fields to return.' },
    ],
  },
  {
    id: 'sites-search',
    group: 'SharePoint — Sites',
    name: 'Search Sites',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/sites',
    description: 'Searches for SharePoint sites matching a keyword.',
    params: [
      { key: 'search', type: 'query', required: true, hint: 'e.g. marketing', description: 'Keyword to search for in site names.' },
    ],
  },
  {
    id: 'sites-get-subsites',
    group: 'SharePoint — Sites',
    name: 'Get Sub-Sites',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/sites/{siteId}/sites',
    description: 'Returns all sub-sites of a SharePoint site.',
    params: [
      { key: 'siteId', type: 'path', required: true, hint: 'e.g. invenrainc.sharepoint.com,c1fe937c-...,9972906e-...', description: 'Full composite site ID (hostName,siteId,webId).' },
    ],
  },
  {
    id: 'sites-get-permissions',
    group: 'SharePoint — Sites',
    name: 'Get Site Permissions',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/sites/{siteId}/permissions',
    description: 'Returns all permission grants for a SharePoint site.',
    params: [
      { key: 'domain',  type: 'path', required: true, hint: 'e.g. momentumltd.eu', description: 'Your M365 tenant domain.' },
      { key: 'siteId',  type: 'path', required: true, hint: 'e.g. a0de512f-edb4-4337-8fa5-aff528f0dc87', description: 'SharePoint site ID.' },
    ],
  },
  {
    id: 'sites-get-drives',
    group: 'SharePoint — Sites',
    name: 'List Site Drives (Document Libraries)',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/sites/{siteId}/drives',
    description: 'Returns all document libraries (drives) in a SharePoint site.',
    params: [
      { key: 'domain',  type: 'path',  required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'siteId',  type: 'path',  required: true, hint: 'e.g. site ID', description: 'SharePoint site ID.' },
      { key: '$select', type: 'query', required: false, hint: 'e.g. id,name,driveType,webUrl', description: 'Fields to return.' },
    ],
  },
  {
    id: 'sites-get-columns',
    group: 'SharePoint — Sites',
    name: 'List Site Columns',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/sites/{siteId}/columns',
    description: 'Returns all columns defined at the site level.',
    params: [
      { key: 'domain', type: 'path', required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'siteId', type: 'path', required: true, hint: 'e.g. site ID', description: 'SharePoint site ID.' },
    ],
  },

  // ── SHAREPOINT — Lists & Items ────────────────────────────────────────────
  {
    id: 'lists-get',
    group: 'SharePoint — Lists',
    name: 'List Site Lists',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/sites/{siteId}/lists',
    description: 'Returns all lists and document libraries inside a SharePoint site.',
    params: [
      { key: 'domain',  type: 'path',  required: true, hint: 'e.g. jconnelly.com', description: 'Your M365 tenant domain.' },
      { key: 'siteId',  type: 'path',  required: true, hint: 'e.g. 771098f9-551e-411d-bc37-dc0467860d62,4a901957-...', description: 'SharePoint site ID.' },
      { key: '$select', type: 'query', required: false, hint: 'e.g. id,displayName,list,webUrl', description: 'Fields to return.' },
    ],
  },
  {
    id: 'lists-get-by-id',
    group: 'SharePoint — Lists',
    name: 'Get List',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/sites/{siteId}/lists/{listId}',
    description: 'Returns details for a specific SharePoint list or document library.',
    params: [
      { key: 'domain',  type: 'path', required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'siteId',  type: 'path', required: true, hint: 'e.g. site ID', description: 'SharePoint site ID.' },
      { key: 'listId',  type: 'path', required: true, hint: 'e.g. 9c2600b5-d6c2-445d-b3e2-bf2f8ce54eed', description: 'List ID.' },
    ],
  },
  {
    id: 'lists-create',
    group: 'SharePoint — Lists',
    name: 'Create List',
    method: 'POST',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/sites/{siteId}/lists',
    description: 'Creates a new list in a SharePoint site.',
    params: [
      { key: 'domain',          type: 'path', required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'siteId',          type: 'path', required: true, hint: 'e.g. site ID', description: 'SharePoint site ID.' },
      { key: 'displayName',     type: 'body', required: true, hint: 'e.g. Project Tracker', description: 'List display name.' },
      { key: 'list.template',   type: 'body', required: false, hint: 'e.g. genericList', description: 'List template: genericList, documentLibrary.' },
    ],
  },
  {
    id: 'list-items-list',
    group: 'SharePoint — Lists',
    name: 'List Items in List',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/sites/{siteId}/lists/{listId}/items',
    description: 'Returns items in a SharePoint list or document library.',
    params: [
      { key: 'domain',    type: 'path',  required: true, hint: 'e.g. jconnelly.com', description: 'Your M365 tenant domain.' },
      { key: 'siteId',    type: 'path',  required: true, hint: 'e.g. 771098f9-551e-411d-bc37-dc0467860d62,...', description: 'SharePoint site ID.' },
      { key: 'listId',    type: 'path',  required: true, hint: 'e.g. 9c2600b5-d6c2-445d-b3e2-bf2f8ce54eed', description: 'List or library ID.' },
      { key: '$expand',   type: 'query', required: false, hint: 'e.g. fields', description: 'Expand related resources (fields, driveItem).' },
      { key: '$select',   type: 'query', required: false, hint: 'e.g. id,createdDateTime,fields', description: 'Fields to return.' },
      { key: '$top',      type: 'query', required: false, hint: 'e.g. 100', description: 'Max items per page.' },
      { key: '$skiptoken',type: 'query', required: false, hint: 'e.g. <skiptoken from @odata.nextLink>', description: 'Pagination skip token.' },
    ],
  },
  {
    id: 'list-items-get',
    group: 'SharePoint — Lists',
    name: 'Get List Item',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/sites/{siteId}/lists/{listId}/items/{itemId}',
    description: 'Returns a single item from a SharePoint list.',
    params: [
      { key: 'domain',  type: 'path', required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'siteId',  type: 'path', required: true, hint: 'e.g. site ID', description: 'SharePoint site ID.' },
      { key: 'listId',  type: 'path', required: true, hint: 'e.g. list ID', description: 'List ID.' },
      { key: 'itemId',  type: 'path', required: true, hint: 'e.g. 1', description: 'List item ID (numeric).' },
      { key: '$expand', type: 'query', required: false, hint: 'e.g. fields', description: 'Expand field values.' },
    ],
  },
  {
    id: 'list-items-create',
    group: 'SharePoint — Lists',
    name: 'Create List Item',
    method: 'POST',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/sites/{siteId}/lists/{listId}/items',
    description: 'Creates a new item in a SharePoint list.',
    params: [
      { key: 'domain',  type: 'path', required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'siteId',  type: 'path', required: true, hint: 'e.g. site ID', description: 'SharePoint site ID.' },
      { key: 'listId',  type: 'path', required: true, hint: 'e.g. list ID', description: 'List ID.' },
      { key: 'fields',  type: 'body', required: true, hint: 'e.g. {"Title": "My Item", "Status": "Active"}', description: 'Field values for the new list item.' },
    ],
  },
  {
    id: 'list-items-update',
    group: 'SharePoint — Lists',
    name: 'Update List Item',
    method: 'PATCH',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/sites/{siteId}/lists/{listId}/items/{itemId}/fields',
    description: 'Updates field values for a SharePoint list item.',
    params: [
      { key: 'domain',  type: 'path', required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'siteId',  type: 'path', required: true, hint: 'e.g. site ID', description: 'SharePoint site ID.' },
      { key: 'listId',  type: 'path', required: true, hint: 'e.g. list ID', description: 'List ID.' },
      { key: 'itemId',  type: 'path', required: true, hint: 'e.g. 1', description: 'List item ID (numeric).' },
      { key: 'Title',   type: 'body', required: false, hint: 'e.g. Updated Title', description: 'Example field — use your actual field names.' },
    ],
  },
  {
    id: 'list-items-delete',
    group: 'SharePoint — Lists',
    name: 'Delete List Item',
    method: 'DELETE',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/sites/{siteId}/lists/{listId}/items/{itemId}',
    description: 'Deletes a specific item from a SharePoint list.',
    params: [
      { key: 'domain',  type: 'path', required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'siteId',  type: 'path', required: true, hint: 'e.g. site ID', description: 'SharePoint site ID.' },
      { key: 'listId',  type: 'path', required: true, hint: 'e.g. list ID', description: 'List ID.' },
      { key: 'itemId',  type: 'path', required: true, hint: 'e.g. 1', description: 'List item ID.' },
    ],
  },

  // ── SHAREPOINT — Drives (SPO Document Libraries) ──────────────────────────
  {
    id: 'spo-drive-list-folder-children',
    group: 'SharePoint — Drives',
    name: 'List Drive Folder Children (SPO)',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/drives/{driveId}/items/{itemId}/children',
    description: 'Lists files and folders inside a SharePoint document library folder.',
    params: [
      { key: 'domain',  type: 'path',  required: true, hint: 'e.g. shuaa.com', description: 'Your M365 tenant domain.' },
      { key: 'driveId', type: 'path',  required: true, hint: 'e.g. b!Lev00HNSgEaYDTJDSBXZ4-6eZd_3yJVKtZs...', description: 'SharePoint drive ID.' },
      { key: 'itemId',  type: 'path',  required: true, hint: 'e.g. root  or  013RJMSJWOZ76GLICRFFAZ67GM6JEZDZG6', description: 'Folder item ID. Use root for top-level.' },
      { key: '$select', type: 'query', required: false, hint: 'e.g. id,name,size,folder,file,webUrl', description: 'Fields to return.' },
      { key: '$top',    type: 'query', required: false, hint: 'e.g. 100', description: 'Max items per page.' },
    ],
  },
  {
    id: 'spo-drive-get-item-permissions',
    group: 'SharePoint — Drives',
    name: 'Get Drive Folder Permissions (SPO)',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/drives/{driveId}/items/{itemId}/permissions',
    description: 'Returns the permissions for a folder inside a SharePoint document library.',
    params: [
      { key: 'domain',  type: 'path', required: true, hint: 'e.g. shuaa.com', description: 'Your M365 tenant domain.' },
      { key: 'driveId', type: 'path', required: true, hint: 'e.g. b!Lev00HNSgEaYDTJDSBXZ47pNKkaGTedGv3t22OA1B9lk...', description: 'SharePoint drive ID.' },
      { key: 'itemId',  type: 'path', required: true, hint: 'e.g. 01F65WHUBQIK24DGOYJ5AIAMEYWWFRNZ2F', description: 'Folder or file item ID.' },
    ],
  },
  {
    id: 'spo-drive-get-root',
    group: 'SharePoint — Drives',
    name: 'Get Drive Root (SPO)',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/drives/{driveId}/root',
    description: 'Returns the root folder of a SharePoint document library.',
    params: [
      { key: 'domain',  type: 'path', required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'driveId', type: 'path', required: true, hint: 'e.g. drive ID from List Site Drives', description: 'SharePoint drive ID.' },
    ],
  },
  {
    id: 'spo-drive-search',
    group: 'SharePoint — Drives',
    name: 'Search Drive Items (SPO)',
    method: 'GET',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/drives/{driveId}/root/search(q=\'{searchText}\')',
    description: 'Searches for files and folders within a SharePoint document library.',
    params: [
      { key: 'domain',     type: 'path',  required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'driveId',    type: 'path',  required: true, hint: 'e.g. drive ID', description: 'SharePoint drive ID.' },
      { key: 'searchText', type: 'path',  required: true, hint: 'e.g. invoice', description: 'Search keyword.' },
      { key: '$select',    type: 'query', required: false, hint: 'e.g. id,name,webUrl,size', description: 'Fields to return.' },
    ],
  },
  {
    id: 'spo-drive-create-folder',
    group: 'SharePoint — Drives',
    name: 'Create Folder (SPO Drive)',
    method: 'POST',
    baseUrl: 'https://graph.microsoft.com/v1.0/{domain}/drives/{driveId}/items/{parentItemId}/children',
    description: 'Creates a new folder in a SharePoint document library.',
    params: [
      { key: 'domain',        type: 'path', required: true, hint: 'e.g. contoso.com', description: 'Your M365 tenant domain.' },
      { key: 'driveId',       type: 'path', required: true, hint: 'e.g. drive ID', description: 'SharePoint drive ID.' },
      { key: 'parentItemId',  type: 'path', required: true, hint: 'e.g. root or parent folder ID', description: 'Parent folder item ID.' },
      { key: 'name',          type: 'body', required: true, hint: 'e.g. New Reports Folder', description: 'New folder name.' },
      { key: 'folder',        type: 'body', required: true, hint: 'e.g. {}', description: 'Empty object — signals folder creation.' },
    ],
  },
];
